// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package writer

// OutputDir 指定输出目录；为空时输出到结构体源文件的同级目录。
// GetOutputDir 获取 OutputDir
func (this *Config) GetOutputDir() string {
	return this.OutputDir
}

// SetOutputDir 设置 OutputDir
func (this *Config) SetOutputDir(OutputDir string) {
	this.OutputDir = OutputDir
}

// Suffix 是生成文件名中下划线后的部分，默认为 "access"（即 user_access.go）。
// 自定义示例：Suffix="gen" → user_gen.go；Suffix="gogen" → user_gogen.go。
// GetSuffix 获取 Suffix
func (this *Config) GetSuffix() string {
	return this.Suffix
}

// SetSuffix 设置 Suffix
func (this *Config) SetSuffix(Suffix string) {
	this.Suffix = Suffix
}

// DryRun 为 true 时只打印将要生成的文件路径，不实际写入。
// GetDryRun 获取 DryRun
func (this *Config) GetDryRun() bool {
	return this.DryRun
}

// SetDryRun 设置 DryRun
func (this *Config) SetDryRun(DryRun bool) {
	this.DryRun = DryRun
}

// ToggleDryRun 翻转 DryRun 的布尔值
func (this *Config) ToggleDryRun() {
	this.DryRun = !this.DryRun
}

// Verbose 为 true 时输出详细日志。
// GetVerbose 获取 Verbose
func (this *Config) GetVerbose() bool {
	return this.Verbose
}

// SetVerbose 设置 Verbose
func (this *Config) SetVerbose(Verbose bool) {
	this.Verbose = Verbose
}

// ToggleVerbose 翻转 Verbose 的布尔值
func (this *Config) ToggleVerbose() {
	this.Verbose = !this.Verbose
}
