// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 创建日期: 2026-03-06 16:49:47
// 该文件为自动生成，请勿修改！

package writer

// OutputDir 指定输出目录；为空时输出到结构体源文件的同级目录。
// GetOutputDir 获取 OutputDir
func (this *Config) GetOutputDir() string {
	return this.OutputDir
}

// SetOutputDir 设置 OutputDir
func (this *Config) SetOutputDir(OutputDir string) {
	this.OutputDir = OutputDir
}

// DryRun 为 true 时只打印将要生成的文件路径，不实际写入。
// GetDryRun 获取 DryRun
func (this *Config) GetDryRun() bool {
	return this.DryRun
}

// SetDryRun 设置 DryRun
func (this *Config) SetDryRun(DryRun bool) {
	this.DryRun = DryRun
}

// Verbose 为 true 时输出详细日志。
// GetVerbose 获取 Verbose
func (this *Config) GetVerbose() bool {
	return this.Verbose
}

// SetVerbose 设置 Verbose
func (this *Config) SetVerbose(Verbose bool) {
	this.Verbose = Verbose
}
