// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 作者:  yangyuan
// 创建日期: 2025/7/31

package writer_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/motocat46/gogen/pkg/model"
	"github.com/motocat46/gogen/pkg/writer"
)

// makeStruct 创建一个最小的 StructDef，用于 writer 测试。
func makeStruct(dir, pkgName, name string) *model.StructDef {
	return &model.StructDef{
		Name:        name,
		PackageName: pkgName,
		Dir:         dir,
	}
}

// gogenCode 模拟已格式化的 gogen 生成内容（含必要标记）。
const gogenCode = `// Code generated by gogen; DO NOT EDIT.

package example

// GetFoo 获取 Foo
func (this *MyStruct) GetFoo() string {
	return this.Foo
}
`

// handWrittenCode 模拟手写文件（不含生成标记）。
const handWrittenCode = `package example

// GetFoo 手写实现
func (this *MyStruct) GetFoo() string {
	return "custom"
}
`

// TestWrite_NewFile 验证目标文件不存在时正常写入并返回 written=true。
func TestWrite_NewFile(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	written, err := writer.Write(s, []byte(gogenCode), cfg)
	if err != nil {
		t.Fatalf("Write 失败: %v", err)
	}
	if !written {
		t.Error("期望 written=true，实际为 false")
	}

	outPath := filepath.Join(dir, "mystruct_access.go")
	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Errorf("期望文件 %s 存在，但不存在", outPath)
	}
}

// TestWrite_SameContent_Skip 验证已有相同内容时增量跳过（written=false）。
func TestWrite_SameContent_Skip(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	// 第一次写入
	if _, err := writer.Write(s, []byte(gogenCode), cfg); err != nil {
		t.Fatalf("第一次 Write 失败: %v", err)
	}

	// 第二次写入相同内容
	written, err := writer.Write(s, []byte(gogenCode), cfg)
	if err != nil {
		t.Fatalf("第二次 Write 失败: %v", err)
	}
	if written {
		t.Error("期望 written=false（内容不变，跳过），实际为 true")
	}
}

// TestWrite_DifferentContent_Overwrite 验证已有不同内容时覆盖写入（written=true）。
func TestWrite_DifferentContent_Overwrite(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	// 写入原始内容
	if _, err := writer.Write(s, []byte(gogenCode), cfg); err != nil {
		t.Fatalf("第一次 Write 失败: %v", err)
	}

	// 写入修改后的内容（仍含 gogen 标记）
	updatedCode := strings.Replace(gogenCode, "GetFoo", "GetBar", 1)
	written, err := writer.Write(s, []byte(updatedCode), cfg)
	if err != nil {
		t.Fatalf("第二次 Write 失败: %v", err)
	}
	if !written {
		t.Error("期望 written=true（内容不同），实际为 false")
	}
}

// TestWrite_HandWrittenFile_Rejected 验证手写文件（无 gogen 标记）拒绝覆盖并返回 error。
func TestWrite_HandWrittenFile_Rejected(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	// 预先写入手写文件（无 gogen 标记）
	outPath := filepath.Join(dir, cfg.OutputFilename(s.Name))
	if err := os.WriteFile(outPath, []byte(handWrittenCode), 0o644); err != nil {
		t.Fatalf("预写入手写文件失败: %v", err)
	}

	written, err := writer.Write(s, []byte(gogenCode), cfg)
	if err == nil {
		t.Error("期望返回 error（手写文件保护），实际为 nil")
	}
	if written {
		t.Error("期望 written=false，实际为 true")
	}
}

// TestWrite_DryRun 验证 dry-run 模式下不创建文件，返回 written=false。
func TestWrite_DryRun(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access", DryRun: true}

	written, err := writer.Write(s, []byte(gogenCode), cfg)
	if err != nil {
		t.Fatalf("Write DryRun 失败: %v", err)
	}
	if written {
		t.Error("dry-run 模式期望 written=false，实际为 true")
	}

	outPath := filepath.Join(dir, cfg.OutputFilename(s.Name))
	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Errorf("dry-run 模式不应创建文件 %s", outPath)
	}
}

// TestWrite_CustomSuffix 验证 Suffix 配置生效（文件名使用自定义后缀）。
func TestWrite_CustomSuffix(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "gen"}

	written, err := writer.Write(s, []byte(gogenCode), cfg)
	if err != nil {
		t.Fatalf("Write 自定义后缀失败: %v", err)
	}
	if !written {
		t.Error("期望 written=true，实际为 false")
	}

	expectedPath := filepath.Join(dir, "mystruct_gen.go")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("期望文件 %s 存在，但不存在", expectedPath)
	}
}

// TestWrite_DefaultSuffix 验证 Suffix 为空时使用 DefaultSuffix。
func TestWrite_DefaultSuffix(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{} // Suffix 为空

	written, err := writer.Write(s, []byte(gogenCode), cfg)
	if err != nil {
		t.Fatalf("Write 默认后缀失败: %v", err)
	}
	if !written {
		t.Error("期望 written=true，实际为 false")
	}

	// 默认后缀为 "access"
	expectedPath := filepath.Join(dir, "mystruct_access.go")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("期望文件 %s 存在（默认后缀），但不存在", expectedPath)
	}
}

// TestClean_ExistingGogenFile 验证 Clean 删除已有的 gogen 生成文件。
func TestClean_ExistingGogenFile(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	// 先写入 gogen 文件
	if _, err := writer.Write(s, []byte(gogenCode), cfg); err != nil {
		t.Fatalf("Write 失败: %v", err)
	}

	// 调用 Clean
	if err := writer.Clean(s, cfg); err != nil {
		t.Fatalf("Clean 失败: %v", err)
	}

	outPath := filepath.Join(dir, cfg.OutputFilename(s.Name))
	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Errorf("Clean 后文件 %s 应不存在", outPath)
	}
}

// TestClean_NonExistentFile 验证 Clean 对不存在的文件不报错。
func TestClean_NonExistentFile(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	// 文件不存在时 Clean 应无错误
	if err := writer.Clean(s, cfg); err != nil {
		t.Fatalf("Clean 对不存在文件不应报错，实际: %v", err)
	}
}

// TestClean_DryRun 验证 Clean dry-run 模式不删除文件。
func TestClean_DryRun(t *testing.T) {
	dir := t.TempDir()
	s := makeStruct(dir, "example", "MyStruct")
	cfg := writer.Config{Suffix: "access"}

	// 先写入文件
	if _, err := writer.Write(s, []byte(gogenCode), cfg); err != nil {
		t.Fatalf("Write 失败: %v", err)
	}

	// dry-run Clean 不应删除
	dryRunCfg := writer.Config{Suffix: "access", DryRun: true}
	if err := writer.Clean(s, dryRunCfg); err != nil {
		t.Fatalf("Clean DryRun 失败: %v", err)
	}

	outPath := filepath.Join(dir, cfg.OutputFilename(s.Name))
	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Errorf("dry-run 模式不应删除文件 %s", outPath)
	}
}

// TestOutputFilename 验证 OutputFilename 生成正确的文件名。
func TestOutputFilename(t *testing.T) {
	cases := []struct {
		suffix   string
		name     string
		expected string
	}{
		{"access", "User", "user_access.go"},
		{"gen", "UserProfile", "userprofile_gen.go"},
		{"", "Foo", "foo_access.go"}, // 空后缀使用默认值
		{"access", "MyStruct", "mystruct_access.go"},
	}

	for _, tc := range cases {
		cfg := writer.Config{Suffix: tc.suffix}
		got := cfg.OutputFilename(tc.name)
		if got != tc.expected {
			t.Errorf("OutputFilename(%q, suffix=%q) = %q，期望 %q", tc.name, tc.suffix, got, tc.expected)
		}
	}
}
