// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package linter

import "go/token"

// GetPos 获取 Pos
func (this *Issue) GetPos() token.Position {
	return this.Pos
}

// SetPos 设置 Pos
func (this *Issue) SetPos(Pos token.Position) {
	this.Pos = Pos
}

// GetSeverity 获取 Severity
func (this *Issue) GetSeverity() Severity {
	return this.Severity
}

// SetSeverity 设置 Severity
func (this *Issue) SetSeverity(Severity Severity) {
	this.Severity = Severity
}

// AddSeverity 将 Severity 增加 delta
func (this *Issue) AddSeverity(delta Severity) {
	this.Severity += delta
}

// SubSeverity 将 Severity 减少 delta
func (this *Issue) SubSeverity(delta Severity) {
	this.Severity -= delta
}

// GetMessage 获取 Message
func (this *Issue) GetMessage() string {
	return this.Message
}

// SetMessage 设置 Message
func (this *Issue) SetMessage(Message string) {
	this.Message = Message
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *Issue) Reset() {
	*this = Issue{}
}
