// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package loader

import "slices"

// ExcludePaths 为排除规则，与 analyzer.Config.ExcludePaths 语义一致：
//   - 绝对路径或含路径分隔符的路径：前缀匹配
//   - 纯目录名（如 "mock"、"mocks"）：匹配路径中任意一段
//
// GetExcludePathsAt 获取切片 ExcludePaths 中 index 位置的元素
func (this *Config) GetExcludePathsAt(index int) string {
	return this.ExcludePaths[index]
}

// GetExcludePathsLen 获取切片 ExcludePaths 的长度
func (this *Config) GetExcludePathsLen() int {
	return len(this.ExcludePaths)
}

// RangeExcludePaths 遍历切片 ExcludePaths，fn 返回 false 时终止遍历
func (this *Config) RangeExcludePaths(fn func(index int, value string) bool) {
	for i, v := range this.ExcludePaths {
		if !fn(i, v) {
			break
		}
	}
}

// HasExcludePaths 返回切片 ExcludePaths 是否已初始化（非 nil）
func (this *Config) HasExcludePaths() bool {
	return this.ExcludePaths != nil
}

// GetExcludePathsCopy 返回切片 ExcludePaths 的浅拷贝
func (this *Config) GetExcludePathsCopy() []string {
	return slices.Clone(this.ExcludePaths)
}

// SetExcludePathsAt 设置切片 ExcludePaths 中 index 位置的元素
func (this *Config) SetExcludePathsAt(index int, elem string) {
	this.ExcludePaths[index] = elem
}

// AppendExcludePaths 向切片 ExcludePaths 追加一个或多个元素
func (this *Config) AppendExcludePaths(elems ...string) {
	this.ExcludePaths = append(this.ExcludePaths, elems...)
}

// DeleteExcludePathsAt 删除切片 ExcludePaths 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *Config) DeleteExcludePathsAt(index int) {
	this.ExcludePaths = slices.Delete(this.ExcludePaths, index, index+1)
}

// GeneratedSuffix 是 gogen 生成文件的名称后缀（不含下划线和 .go 扩展名）。
// 例如 "access" 表示匹配 *_access.go；"gen" 表示匹配 *_gen.go。
// 为空时使用默认值 "access"。
// GetGeneratedSuffix 获取 GeneratedSuffix
func (this *Config) GetGeneratedSuffix() string {
	return this.GeneratedSuffix
}

// SetGeneratedSuffix 设置 GeneratedSuffix
func (this *Config) SetGeneratedSuffix(GeneratedSuffix string) {
	this.GeneratedSuffix = GeneratedSuffix
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *Config) Reset() {
	*this = Config{}
}
