// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 作者:  yangyuan
// 创建日期: 2026/4/8

// 内部测试文件：覆盖包私有函数 packageDir、isExcludedPath、normalizePatterns 和 readGogenFilePkg。
package loader

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"
)

// ─── packageDir ───────────────────────────────────────────────────────────────

func TestPackageDir(t *testing.T) {
	tests := []struct {
		name    string
		goFiles []string
		want    string
	}{
		{
			name:    "有 GoFiles，返回第一个文件所在目录",
			goFiles: []string{filepath.Join("/project", "pkg", "foo", "foo.go")},
			want:    filepath.Join("/project", "pkg", "foo"),
		},
		{
			name:    "GoFiles 为空，返回空字符串",
			goFiles: nil,
			want:    "",
		},
		{
			name:    "多个文件，取第一个文件所在目录",
			goFiles: []string{filepath.Join("/a", "b.go"), filepath.Join("/a", "c.go")},
			want:    "/a",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			pkg := &packages.Package{GoFiles: tt.goFiles}
			assert.Equal(t, tt.want, packageDir(pkg))
		})
	}
}

// ─── isExcludedPath ───────────────────────────────────────────────────────────

func TestIsExcludedPath(t *testing.T) {
	sep := string(filepath.Separator)

	tests := []struct {
		name     string
		path     string
		excludes []string
		want     bool
	}{
		{
			name:     "空排除列表",
			path:     sep + filepath.Join("project", "pkg", "foo.go"),
			excludes: nil,
			want:     false,
		},
		{
			name:     "纯目录名匹配路径中某段",
			path:     sep + filepath.Join("project", "mock", "service.go"),
			excludes: []string{"mock"},
			want:     true,
		},
		{
			name:     "纯目录名不匹配",
			path:     sep + filepath.Join("project", "service", "logic.go"),
			excludes: []string{"mock"},
			want:     false,
		},
		{
			name:     "含分隔符的规则：前缀匹配命中",
			path:     sep + filepath.Join("project", "testdata", "foo.go"),
			excludes: []string{sep + filepath.Join("project", "testdata")},
			want:     true,
		},
		{
			name:     "含分隔符的规则：前缀不匹配",
			path:     sep + filepath.Join("project", "pkg", "foo.go"),
			excludes: []string{sep + filepath.Join("project", "testdata")},
			want:     false,
		},
		{
			name:     "多规则命中第二条",
			path:     sep + filepath.Join("project", "generated", "types.go"),
			excludes: []string{"mock", "generated"},
			want:     true,
		},
		{
			name:     "多规则均未命中",
			path:     sep + filepath.Join("project", "internal", "logic.go"),
			excludes: []string{"mock", "generated"},
			want:     false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, isExcludedPath(tt.path, tt.excludes))
		})
	}
}

// ─── normalizePatterns ────────────────────────────────────────────────────────

func TestNormalizePatterns(t *testing.T) {
	dir := "/some/project"

	tests := []struct {
		name     string
		patterns []string
		want     []string
	}{
		{
			name:     "非 .go 路径原样保留",
			patterns: []string{".", "./..."},
			want:     []string{".", "./..."},
		},
		{
			name:     "相对 .go 路径转换为绝对 file= 格式",
			patterns: []string{"./foo.go"},
			want:     []string{"file=" + filepath.Join(dir, "./foo.go")},
		},
		{
			name:     "绝对 .go 路径转换为 file= 格式（不再拼接 dir）",
			patterns: []string{"/abs/path/foo.go"},
			want:     []string{"file=/abs/path/foo.go"},
		},
		{
			name:     "已是 file= 格式原样保留",
			patterns: []string{"file=foo.go"},
			want:     []string{"file=foo.go"},
		},
		{
			name:     "混合：.go 文件与包路径",
			patterns: []string{"./bar.go", "./..."},
			want:     []string{"file=" + filepath.Join(dir, "./bar.go"), "./..."},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := normalizePatterns(dir, tt.patterns)
			require.Len(t, got, len(tt.want))
			for i := range got {
				assert.Equal(t, tt.want[i], got[i])
			}
		})
	}
}

// ─── readGogenFilePkg ─────────────────────────────────────────────────────────

func TestReadGogenFilePkg(t *testing.T) {
	t.Run("文件不存在时返回空字符串和 false", func(t *testing.T) {
		pkgName, isGogen := readGogenFilePkg("/nonexistent/path/file.go")
		assert.Empty(t, pkgName)
		assert.False(t, isGogen)
	})

	t.Run("gogen 生成文件返回包名和 true", func(t *testing.T) {
		content := "// Code generated by gogen; DO NOT EDIT.\n\npackage mypkg\n"
		tmp, err := os.CreateTemp(t.TempDir(), "*.go")
		require.NoError(t, err)
		_, err = tmp.WriteString(content)
		require.NoError(t, err)
		require.NoError(t, tmp.Close())

		pkgName, isGogen := readGogenFilePkg(tmp.Name())
		assert.Equal(t, "mypkg", pkgName)
		assert.True(t, isGogen)
	})

	t.Run("非 gogen 文件只返回包名和 false", func(t *testing.T) {
		content := "package otherpkg\n\nfunc Foo() {}\n"
		tmp, err := os.CreateTemp(t.TempDir(), "*.go")
		require.NoError(t, err)
		_, err = tmp.WriteString(content)
		require.NoError(t, err)
		require.NoError(t, tmp.Close())

		pkgName, isGogen := readGogenFilePkg(tmp.Name())
		assert.Equal(t, "otherpkg", pkgName)
		assert.False(t, isGogen)
	})
}

// ─── filterExcludedPackages ───────────────────────────────────────────────────

func TestFilterExcludedPackages_EmptyGoFiles(t *testing.T) {
	// 包含一个 GoFiles 为空的包（dir="")：排除路径不匹配，不应被过滤
	pkgNoFiles := &packages.Package{GoFiles: nil}
	pkgWithFiles := &packages.Package{GoFiles: []string{"/project/pkg/foo.go"}}

	result := filterExcludedPackages(
		[]*packages.Package{pkgNoFiles, pkgWithFiles},
		[]string{"/project/pkg"},
	)
	// pkgNoFiles.dir="" 不匹配排除规则，不被过滤
	// pkgWithFiles.dir="/project/pkg" 匹配排除规则，被过滤
	assert.Len(t, result, 1, "只有 GoFiles 为空的包应保留，另一个应被过滤")
	assert.Equal(t, pkgNoFiles, result[0])
}
