// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 作者:  yangyuan
// 创建日期: 2025/7/31

package loader_test

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/motocat46/gogen/pkg/loader"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// examplesDir 返回 testdata/examples 的绝对路径。
func examplesDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	require.True(t, ok, "无法获取当前文件路径")
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "testdata", "examples")
}

// makeTempModule 在临时目录创建一个最小 Go 模块，写入指定文件内容，返回模块目录。
func makeTempModule(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()

	// 写入 go.mod
	gomod := "module testmod\n\ngo 1.22\n"
	err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0o644)
	require.NoError(t, err, "写入 go.mod 失败")

	// 写入用户指定的文件
	for name, content := range files {
		path := filepath.Join(dir, name)
		err := os.MkdirAll(filepath.Dir(path), 0o755)
		require.NoError(t, err, "创建目录失败")
		err = os.WriteFile(path, []byte(content), 0o644)
		require.NoError(t, err, "写入文件 %s 失败", name)
	}
	return dir
}

// TestLoad_BasicSuccess 验证正常包可以成功加载。
func TestLoad_BasicSuccess(t *testing.T) {
	dir := examplesDir(t)
	pkgs, err := loader.Load(dir, loader.Config{}, ".")
	require.NoError(t, err, "Load 失败")
	require.NotEmpty(t, pkgs, "期望至少加载到 1 个包")
	// 验证包含类型信息（TypesInfo 非 nil）
	for _, pkg := range pkgs {
		assert.NotNil(t, pkg.TypesInfo, "包 %s 缺少 TypesInfo", pkg.PkgPath)
	}
}

// TestLoad_ExcludePaths 验证被排除的包不出现在结果中。
func TestLoad_ExcludePaths(t *testing.T) {
	dir := examplesDir(t)
	// 将 examples 目录本身加入排除路径 → 结果应为空
	pkgs, err := loader.Load(dir, loader.Config{ExcludePaths: []string{dir}}, ".")
	require.NoError(t, err, "Load 失败")
	assert.Empty(t, pkgs, "期望排除后结果为空")
}

// TestLoad_SingleGoFile 验证传入单个 .go 文件路径时能加载其所在的完整包。
func TestLoad_SingleGoFile(t *testing.T) {
	dir := examplesDir(t)
	// 取 examples 目录下第一个 .go 文件
	entries, err := os.ReadDir(dir)
	require.NoError(t, err, "读取目录失败")

	var goFile string
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".go" &&
			!strings.HasSuffix(e.Name(), "_test.go") &&
			e.Name() != "." && len(e.Name()) > 3 {
			goFile = filepath.Join(dir, e.Name())
			break
		}
	}
	if goFile == "" {
		t.Skip("testdata/examples 中无 .go 文件")
	}

	// 使用相对路径传入（normalizePatterns 应将其转换为 file= 格式）
	pkgs, err := loader.Load(dir, loader.Config{}, goFile)
	require.NoError(t, err, "Load 单个文件失败")
	require.NotEmpty(t, pkgs, "期望加载到至少 1 个包")
}

// TestLoad_TwoPhase_DefaultSuffix 验证两阶段加载的核心场景：
// 当 *_access.go（gogen 生成文件）含编译错误时，Load 应自动 overlay 恢复，而不是报错退出。
func TestLoad_TwoPhase_DefaultSuffix(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		// 正常的源文件
		"user.go": `package testmod

type User struct {
	Name string
	Age  int
}
`,
		// 含 gogen 标记但语法错误的生成文件（模拟旧版本生成的错误文件）
		"user_access.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

INVALID SYNTAX HERE — 模拟生成文件损坏
`,
	})

	// 两阶段加载应能恢复：检测到 user_access.go 有 gogen 标记 → overlay 空包声明 → 加载成功
	pkgs, err := loader.Load(dir, loader.Config{}, ".")
	require.NoError(t, err, "两阶段加载应能恢复损坏的生成文件")
	require.NotEmpty(t, pkgs, "期望加载到至少 1 个包")
}

// TestLoad_TwoPhase_CustomSuffix 验证自定义后缀场景下两阶段加载同样生效。
// 使用 --suffix gen 时，损坏的 *_gen.go 应被恢复；*_access.go 损坏则应报错（属于用户文件）。
func TestLoad_TwoPhase_CustomSuffix(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct {
	Name string
}
`,
		// 使用 gen 后缀的损坏生成文件
		"user_gen.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

BAD CODE
`,
	})

	// suffix=gen → 应能恢复 user_gen.go
	pkgs, err := loader.Load(dir, loader.Config{GeneratedSuffix: "gen"}, ".")
	require.NoError(t, err, "自定义后缀两阶段加载应能恢复损坏文件")
	require.NotEmpty(t, pkgs, "期望加载到至少 1 个包")
}

// TestLoad_TwoPhase_WrongSuffix 验证 suffix 不匹配时，损坏的文件被视为用户错误（报错）。
// 这是 suffix 配置正确性的关键验证：防止不同 suffix 的文件被误判为 gogen 文件。
func TestLoad_TwoPhase_WrongSuffix(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct {
	Name string
}
`,
		// 含 gogen 标记但 suffix=access，而我们用 suffix=gen 运行
		"user_access.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

BAD CODE
`,
	})

	// suffix=gen → user_access.go 不匹配 *_gen.go → 不在 overlay 列表 → 应报错
	_, err := loader.Load(dir, loader.Config{GeneratedSuffix: "gen"}, ".")
	require.Error(t, err, "suffix 不匹配时，损坏的生成文件应视为用户错误并报错")
}

// TestLoad_HandWrittenFileError_NotRecovered 验证无 gogen 标记的文件出错时不自动恢复（应报错）。
// 这保证了手写文件的编译错误不被 gogen 静默吞掉。
func TestLoad_HandWrittenFileError_NotRecovered(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct {
	Name string
}
`,
		// 命名上符合 _access.go 模式，但无 gogen 标记 → 应视为用户文件
		"user_access.go": `package testmod

BAD CODE — 无 gogen 标记，手写文件
`,
	})

	_, err := loader.Load(dir, loader.Config{}, ".")
	require.Error(t, err, "无 gogen 标记的文件编译错误应报错，不应静默恢复")
}

// TestLoad_DefaultSuffix_FallbackToAccess 验证 GeneratedSuffix 为空时默认使用 "access"。
func TestLoad_DefaultSuffix_FallbackToAccess(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct{ Name string }
`,
		"user_access.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

BAD CODE
`,
	})

	// 不传 suffix（空字符串）→ 内部默认 "access" → 应恢复
	pkgs, err := loader.Load(dir, loader.Config{GeneratedSuffix: ""}, ".")
	require.NoError(t, err, "GeneratedSuffix 为空时应默认 access")
	require.NotEmpty(t, pkgs, "期望加载到至少 1 个包")
}

// TestLoad_AccessFileRecovery 验证两阶段加载能恢复损坏的 access 文件。
// 这是对 DESIGN.md 中"两阶段加载"机制的文档级测试：
// 损坏的 *_access.go 会触发 overlay，阶段2重新加载后成功返回包。
func TestLoad_AccessFileRecovery(t *testing.T) {
	src := `package mypkg

type Foo struct {
	Name string
}
`
	// 损坏的 access 文件（语法错误，模拟第一次生成后手动破坏）
	brokenAccess := `// Code generated by gogen; DO NOT EDIT.

package mypkg

func (this *Foo) GetName( {
	return this.Name
}
`
	dir := makeTempModule(t, map[string]string{
		"mypkg/foo.go":        src,
		"mypkg/foo_access.go": brokenAccess,
	})

	pkgs, err := loader.Load(filepath.Join(dir, "mypkg"), loader.Config{}, ".")
	require.NoError(t, err, "两阶段加载应成功恢复损坏的 access 文件")
	require.NotEmpty(t, pkgs, "期望加载到至少一个包")
}

// TestLoad_Phase2_OverlaidDirCascadeErrors 验证 phase 2 中 overlaidDirs 包的级联错误被跳过。
//
// 场景：同一个包里既有损坏的 *_access.go（触发 overlay），又有调用生成方法的消费者文件。
// Phase 2 overlay 后消费者文件产生 "undefined" 级联错误，但该包目录在 overlaidDirs 中，
// 应被静默跳过，Load 应成功返回。
func TestLoad_Phase2_OverlaidDirCascadeErrors(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"pkg/user.go": `package pkg
type User struct { Name string }
`,
		// 含 gogen 标记的损坏文件（phase 1 出错 → 触发 overlay）
		// 同时定义了 GetName 方法，overlay 后该方法消失
		"pkg/user_access.go": `// Code generated by gogen; DO NOT EDIT.
package pkg
func (u *User) GetName() string { return u.Name }
INVALID SYNTAX HERE
`,
		// 调用 GetName，overlay 后产生级联 "undefined" 错误
		"pkg/consumer.go": `package pkg
func Greet(u *User) string { return u.GetName() }
`,
		// 辅助包（合法），确保 ./... 加载多个包，覆盖非 overlaid 包的 for 循环路径
		"helper/helper.go": `package helper
func Noop() {}
`,
	})

	// phase1: user_access.go 损坏 → overlay；consumer.go 级联错误 → otherErrs（但 overlay 非空 → 继续）
	// phase2: user_access.go 被 overlay，pkg/ 目录在 overlaidDirs → 级联错误被跳过
	// helper/ 不在 overlaidDirs → 进入 for 循环，但无错误
	pkgs, err := loader.Load(filepath.Join(dir, "pkg"), loader.Config{}, ".")
	require.NoError(t, err, "phase2 中 overlaidDirs 包的级联错误应被跳过")
	require.NotEmpty(t, pkgs, "期望加载到至少一个包")
}

// TestLoad_Phase2_RemainErrors 验证 phase 2 中非 overlaid 包的错误导致 Load 返回 error。
//
// 场景：pkg/ 有损坏的 _access.go（触发 overlay），另有独立的 broken/ 包含用户代码错误。
// phase 2 中 broken/ 不在 overlaidDirs → 其错误进入 remainErrs → Load 报错。
func TestLoad_Phase2_RemainErrors(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"pkg/user.go": `package pkg
type User struct { Name string }
`,
		// 损坏的生成文件 → 触发 overlay
		"pkg/user_access.go": `// Code generated by gogen; DO NOT EDIT.
package pkg
BAD SYNTAX
`,
		// 独立包，含用户代码错误，与 overlay 无关
		"broken/bad.go": `package broken
var _ = undefinedSymbol
`,
	})

	// phase1: user_access.go 错误 → overlay；broken/ 错误 → otherErrs
	// 因 overlay 非空，进入 phase 2
	// phase2: broken/ 不在 overlaidDirs → remainErrs 非空 → 返回 error
	_, err := loader.Load(dir, loader.Config{}, "./...")
	require.Error(t, err, "phase2 中非 overlaid 包的错误应导致 Load 返回 error")
}

// TestLoad_Phase2_MultiPkg_NoErrors 验证 phase 2 访问非 overlaid 包时、该包无错误的路径。
//
// 场景：pkg/ 损坏（触发 overlay），helper/ 合法无错误。
// phase 2 中 helper/ 不在 overlaidDirs → 进入 for range pkg.Errors（空循环），Load 成功。
func TestLoad_Phase2_MultiPkg_NoErrors(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"pkg/user.go": `package pkg
type User struct { Name string }
`,
		"pkg/user_access.go": `// Code generated by gogen; DO NOT EDIT.
package pkg
BAD SYNTAX
`,
		"helper/helper.go": `package helper
func Noop() {}
`,
	})

	pkgs, err := loader.Load(dir, loader.Config{}, "./...")
	require.NoError(t, err, "helper/ 无错误时 Load 应成功")
	require.NotEmpty(t, pkgs, "期望加载到至少一个包")
}

// TestLoad_NoGoFilesSkipped 验证 "no Go files" 错误在 phase 1 和 phase 2 均被静默跳过。
//
// 场景：
//   - pkg/  含损坏的 _access.go → phase 1 触发 overlay → 进入 phase 2
//   - empty/ 是空目录，go/packages 对其报 "no Go files" 错误
//
// 期望：两个阶段都跳过该错误（isNoGoFilesError == true），Load 最终成功。
func TestLoad_NoGoFilesSkipped(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"pkg/user.go": `package pkg
type User struct { Name string }
`,
		// 含 gogen 标记的损坏文件 → phase 1 检测到 → 加入 overlay → 触发 phase 2
		"pkg/user_access.go": `// Code generated by gogen; DO NOT EDIT.
package pkg
BAD SYNTAX
`,
	})
	// 创建空子目录（无 .go 文件），go/packages 对其报 "no Go files"
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "empty"), 0o755))

	// phase 1：pkg/ 的 _access.go 错误 → overlay 非空 → 进入 phase 2
	//          empty/ 的 "no Go files" 错误 → isNoGoFilesError → 静默跳过
	// phase 2：重新加载后 empty/ 仍有 "no Go files" → isNoGoFilesError → 静默跳过
	//          pkg/ 在 overlaidDirs → 跳过
	// 最终 remainErrs 为空 → Load 成功
	pkgs, err := loader.Load(dir, loader.Config{}, "./pkg", "./empty")
	require.NoError(t, err, "'no Go files' 错误应被静默跳过，Load 不应报错")
	require.NotEmpty(t, pkgs, "期望加载到至少一个包")
}

// TestExtractFileFilter 验证从 patterns 中提取显式 .go 文件路径
func TestExtractFileFilter(t *testing.T) {
	dir := "/some/project"

	cases := []struct {
		name     string
		patterns []string
		want     []string
	}{
		{
			name:     "无显式文件时返回空",
			patterns: []string{"./..."},
			want:     nil,
		},
		{
			name:     "相对路径 .go 文件转绝对路径",
			patterns: []string{"./foo.go"},
			want:     []string{filepath.Join(dir, "./foo.go")},
		},
		{
			name:     "绝对路径 .go 文件原样保留",
			patterns: []string{"/abs/path/bar.go"},
			want:     []string{"/abs/path/bar.go"},
		},
		{
			name:     "file= 前缀格式，相对路径",
			patterns: []string{"file=baz.go"},
			want:     []string{filepath.Join(dir, "baz.go")},
		},
		{
			name:     "file= 前缀格式，绝对路径",
			patterns: []string{"file=/abs/baz.go"},
			want:     []string{"/abs/baz.go"},
		},
		{
			name:     "混合：.go 文件 + 包路径 + file= 格式",
			patterns: []string{"./foo.go", "./...", "file=bar.go"},
			want: []string{
				filepath.Join(dir, "./foo.go"),
				filepath.Join(dir, "bar.go"),
			},
		},
		{
			name:     "空 patterns",
			patterns: []string{},
			want:     nil,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := loader.ExtractFileFilter(dir, tc.patterns)
			require.Len(t, got, len(tc.want), "got %v, want %v", got, tc.want)
			for i := range got {
				assert.Equal(t, tc.want[i], got[i])
			}
		})
	}
}
