// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 作者:  yangyuan
// 创建日期: 2025/7/31

package loader_test

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/motocat46/gogen/pkg/loader"
)

// examplesDir 返回 testdata/examples 的绝对路径。
func examplesDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("无法获取当前文件路径")
	}
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "testdata", "examples")
}

// makeTempModule 在临时目录创建一个最小 Go 模块，写入指定文件内容，返回模块目录。
func makeTempModule(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()

	// 写入 go.mod
	gomod := "module testmod\n\ngo 1.22\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0o644); err != nil {
		t.Fatalf("写入 go.mod 失败: %v", err)
	}

	// 写入用户指定的文件
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("创建目录失败: %v", err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("写入文件 %s 失败: %v", name, err)
		}
	}
	return dir
}

// TestLoad_BasicSuccess 验证正常包可以成功加载。
func TestLoad_BasicSuccess(t *testing.T) {
	dir := examplesDir(t)
	pkgs, err := loader.Load(dir, loader.Config{}, ".")
	if err != nil {
		t.Fatalf("Load 失败: %v", err)
	}
	if len(pkgs) == 0 {
		t.Fatal("期望至少加载到 1 个包，实际为 0")
	}
	// 验证包含类型信息（TypesInfo 非 nil）
	for _, pkg := range pkgs {
		if pkg.TypesInfo == nil {
			t.Errorf("包 %s 缺少 TypesInfo", pkg.PkgPath)
		}
	}
}

// TestLoad_ExcludePaths 验证被排除的包不出现在结果中。
func TestLoad_ExcludePaths(t *testing.T) {
	dir := examplesDir(t)
	// 将 examples 目录本身加入排除路径 → 结果应为空
	pkgs, err := loader.Load(dir, loader.Config{ExcludePaths: []string{dir}}, ".")
	if err != nil {
		t.Fatalf("Load 失败: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("期望排除后结果为空，实际有 %d 个包", len(pkgs))
	}
}

// TestLoad_SingleGoFile 验证传入单个 .go 文件路径时能加载其所在的完整包。
func TestLoad_SingleGoFile(t *testing.T) {
	dir := examplesDir(t)
	// 取 examples 目录下第一个 .go 文件
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("读取目录失败: %v", err)
	}
	var goFile string
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".go" &&
			e.Name() != "." && len(e.Name()) > 3 {
			goFile = filepath.Join(dir, e.Name())
			break
		}
	}
	if goFile == "" {
		t.Skip("testdata/examples 中无 .go 文件")
	}

	// 使用相对路径传入（normalizePatterns 应将其转换为 file= 格式）
	pkgs, err := loader.Load(dir, loader.Config{}, goFile)
	if err != nil {
		t.Fatalf("Load 单个文件失败: %v", err)
	}
	if len(pkgs) == 0 {
		t.Fatal("期望加载到至少 1 个包")
	}
}

// TestLoad_TwoPhase_DefaultSuffix 验证两阶段加载的核心场景：
// 当 *_access.go（gogen 生成文件）含编译错误时，Load 应自动 overlay 恢复，而不是报错退出。
func TestLoad_TwoPhase_DefaultSuffix(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		// 正常的源文件
		"user.go": `package testmod

type User struct {
	Name string
	Age  int
}
`,
		// 含 gogen 标记但语法错误的生成文件（模拟旧版本生成的错误文件）
		"user_access.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

INVALID SYNTAX HERE — 模拟生成文件损坏
`,
	})

	// 两阶段加载应能恢复：检测到 user_access.go 有 gogen 标记 → overlay 空包声明 → 加载成功
	pkgs, err := loader.Load(dir, loader.Config{}, ".")
	if err != nil {
		t.Fatalf("两阶段加载应能恢复损坏的生成文件，实际报错: %v", err)
	}
	if len(pkgs) == 0 {
		t.Fatal("期望加载到至少 1 个包")
	}
}

// TestLoad_TwoPhase_CustomSuffix 验证自定义后缀场景下两阶段加载同样生效。
// 使用 --suffix gen 时，损坏的 *_gen.go 应被恢复；*_access.go 损坏则应报错（属于用户文件）。
func TestLoad_TwoPhase_CustomSuffix(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct {
	Name string
}
`,
		// 使用 gen 后缀的损坏生成文件
		"user_gen.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

BAD CODE
`,
	})

	// suffix=gen → 应能恢复 user_gen.go
	pkgs, err := loader.Load(dir, loader.Config{GeneratedSuffix: "gen"}, ".")
	if err != nil {
		t.Fatalf("自定义后缀两阶段加载应能恢复损坏文件，实际报错: %v", err)
	}
	if len(pkgs) == 0 {
		t.Fatal("期望加载到至少 1 个包")
	}
}

// TestLoad_TwoPhase_WrongSuffix 验证 suffix 不匹配时，损坏的文件被视为用户错误（报错）。
// 这是 suffix 配置正确性的关键验证：防止不同 suffix 的文件被误判为 gogen 文件。
func TestLoad_TwoPhase_WrongSuffix(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct {
	Name string
}
`,
		// 含 gogen 标记但 suffix=access，而我们用 suffix=gen 运行
		"user_access.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

BAD CODE
`,
	})

	// suffix=gen → user_access.go 不匹配 *_gen.go → 不在 overlay 列表 → 应报错
	_, err := loader.Load(dir, loader.Config{GeneratedSuffix: "gen"}, ".")
	if err == nil {
		t.Fatal("suffix 不匹配时，损坏的生成文件应视为用户错误并报错")
	}
}

// TestLoad_HandWrittenFileError_NotRecovered 验证无 gogen 标记的文件出错时不自动恢复（应报错）。
// 这保证了手写文件的编译错误不被 gogen 静默吞掉。
func TestLoad_HandWrittenFileError_NotRecovered(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct {
	Name string
}
`,
		// 命名上符合 _access.go 模式，但无 gogen 标记 → 应视为用户文件
		"user_access.go": `package testmod

BAD CODE — 无 gogen 标记，手写文件
`,
	})

	_, err := loader.Load(dir, loader.Config{}, ".")
	if err == nil {
		t.Fatal("无 gogen 标记的文件编译错误应报错，不应静默恢复")
	}
}

// TestLoad_DefaultSuffix_FallbackToAccess 验证 GeneratedSuffix 为空时默认使用 "access"。
func TestLoad_DefaultSuffix_FallbackToAccess(t *testing.T) {
	dir := makeTempModule(t, map[string]string{
		"user.go": `package testmod

type User struct{ Name string }
`,
		"user_access.go": `// Code generated by gogen; DO NOT EDIT.

package testmod

BAD CODE
`,
	})

	// 不传 suffix（空字符串）→ 内部默认 "access" → 应恢复
	pkgs, err := loader.Load(dir, loader.Config{GeneratedSuffix: ""}, ".")
	if err != nil {
		t.Fatalf("GeneratedSuffix 为空时应默认 access，实际报错: %v", err)
	}
	if len(pkgs) == 0 {
		t.Fatal("期望加载到至少 1 个包")
	}
}
