// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package analyzer

import "slices"

// FileFilter 为文件绝对路径列表：非空时只分析这些文件（用户指定具体 .go 文件的场景）。
// GetFileFilterAt 获取切片 FileFilter 中 index 位置的元素
func (this *Config) GetFileFilterAt(index int) string {
	return this.FileFilter[index]
}

// GetFileFilterLen 获取切片 FileFilter 的长度
func (this *Config) GetFileFilterLen() int {
	return len(this.FileFilter)
}

// RangeFileFilter 遍历切片 FileFilter，fn 返回 false 时终止遍历
func (this *Config) RangeFileFilter(fn func(index int, value string) bool) {
	for i, v := range this.FileFilter {
		if !fn(i, v) {
			break
		}
	}
}

// HasFileFilter 返回切片 FileFilter 是否已初始化（非 nil）
func (this *Config) HasFileFilter() bool {
	return this.FileFilter != nil
}

// GetFileFilterCopy 返回切片 FileFilter 的浅拷贝
func (this *Config) GetFileFilterCopy() []string {
	return slices.Clone(this.FileFilter)
}

// SetFileFilterAt 设置切片 FileFilter 中 index 位置的元素
func (this *Config) SetFileFilterAt(index int, elem string) {
	this.FileFilter[index] = elem
}

// AppendFileFilter 向切片 FileFilter 追加一个或多个元素
func (this *Config) AppendFileFilter(elems ...string) {
	this.FileFilter = append(this.FileFilter, elems...)
}

// DeleteFileFilter 删除切片 FileFilter 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *Config) DeleteFileFilter(index int) {
	this.FileFilter = slices.Delete(this.FileFilter, index, index+1)
}

// ExcludePaths 为需要跳过的路径前缀列表，支持目录或文件的绝对路径。
// 例如 ["/project/mocks", "/project/proto"] 会跳过这两个目录下的所有文件。
// GetExcludePathsAt 获取切片 ExcludePaths 中 index 位置的元素
func (this *Config) GetExcludePathsAt(index int) string {
	return this.ExcludePaths[index]
}

// GetExcludePathsLen 获取切片 ExcludePaths 的长度
func (this *Config) GetExcludePathsLen() int {
	return len(this.ExcludePaths)
}

// RangeExcludePaths 遍历切片 ExcludePaths，fn 返回 false 时终止遍历
func (this *Config) RangeExcludePaths(fn func(index int, value string) bool) {
	for i, v := range this.ExcludePaths {
		if !fn(i, v) {
			break
		}
	}
}

// HasExcludePaths 返回切片 ExcludePaths 是否已初始化（非 nil）
func (this *Config) HasExcludePaths() bool {
	return this.ExcludePaths != nil
}

// GetExcludePathsCopy 返回切片 ExcludePaths 的浅拷贝
func (this *Config) GetExcludePathsCopy() []string {
	return slices.Clone(this.ExcludePaths)
}

// SetExcludePathsAt 设置切片 ExcludePaths 中 index 位置的元素
func (this *Config) SetExcludePathsAt(index int, elem string) {
	this.ExcludePaths[index] = elem
}

// AppendExcludePaths 向切片 ExcludePaths 追加一个或多个元素
func (this *Config) AppendExcludePaths(elems ...string) {
	this.ExcludePaths = append(this.ExcludePaths, elems...)
}

// DeleteExcludePaths 删除切片 ExcludePaths 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *Config) DeleteExcludePaths(index int) {
	this.ExcludePaths = slices.Delete(this.ExcludePaths, index, index+1)
}
