// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package analyzer

// GetPlain 获取 Plain
func (this *StructAnnotations) GetPlain() bool {
	return this.Plain
}

// SetPlain 设置 Plain
func (this *StructAnnotations) SetPlain(Plain bool) {
	this.Plain = Plain
}

// TogglePlain 翻转 Plain 的布尔值
func (this *StructAnnotations) TogglePlain() {
	this.Plain = !this.Plain
}

// "" 表示不注入；"MakeDirty" 为默认；自定义名为指定值
// GetDirtyMethod 获取 DirtyMethod
func (this *StructAnnotations) GetDirtyMethod() string {
	return this.DirtyMethod
}

// SetDirtyMethod 设置 DirtyMethod
func (this *StructAnnotations) SetDirtyMethod(DirtyMethod string) {
	this.DirtyMethod = DirtyMethod
}

// gogen:nodirty 显式禁用
// GetNoDirty 获取 NoDirty
func (this *StructAnnotations) GetNoDirty() bool {
	return this.NoDirty
}

// SetNoDirty 设置 NoDirty
func (this *StructAnnotations) SetNoDirty(NoDirty bool) {
	this.NoDirty = NoDirty
}

// ToggleNoDirty 翻转 NoDirty 的布尔值
func (this *StructAnnotations) ToggleNoDirty() {
	this.NoDirty = !this.NoDirty
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *StructAnnotations) Reset() {
	*this = StructAnnotations{}
}
