// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import "time"

// --- 基础类型 ---
// GetFieldBool 获取 FieldBool
func (this *AllTypes) GetFieldBool() bool {
	return this.FieldBool
}

// SetFieldBool 设置 FieldBool
func (this *AllTypes) SetFieldBool(FieldBool bool) {
	this.FieldBool = FieldBool
}

// GetFieldInt 获取 FieldInt
func (this *AllTypes) GetFieldInt() int {
	return this.FieldInt
}

// SetFieldInt 设置 FieldInt
func (this *AllTypes) SetFieldInt(FieldInt int) {
	this.FieldInt = FieldInt
}

// GetFieldInt8 获取 FieldInt8
func (this *AllTypes) GetFieldInt8() int8 {
	return this.FieldInt8
}

// SetFieldInt8 设置 FieldInt8
func (this *AllTypes) SetFieldInt8(FieldInt8 int8) {
	this.FieldInt8 = FieldInt8
}

// GetFieldInt16 获取 FieldInt16
func (this *AllTypes) GetFieldInt16() int16 {
	return this.FieldInt16
}

// SetFieldInt16 设置 FieldInt16
func (this *AllTypes) SetFieldInt16(FieldInt16 int16) {
	this.FieldInt16 = FieldInt16
}

// GetFieldInt32 获取 FieldInt32
func (this *AllTypes) GetFieldInt32() int32 {
	return this.FieldInt32
}

// SetFieldInt32 设置 FieldInt32
func (this *AllTypes) SetFieldInt32(FieldInt32 int32) {
	this.FieldInt32 = FieldInt32
}

// GetFieldInt64 获取 FieldInt64
func (this *AllTypes) GetFieldInt64() int64 {
	return this.FieldInt64
}

// SetFieldInt64 设置 FieldInt64
func (this *AllTypes) SetFieldInt64(FieldInt64 int64) {
	this.FieldInt64 = FieldInt64
}

// GetFieldUint 获取 FieldUint
func (this *AllTypes) GetFieldUint() uint {
	return this.FieldUint
}

// SetFieldUint 设置 FieldUint
func (this *AllTypes) SetFieldUint(FieldUint uint) {
	this.FieldUint = FieldUint
}

// GetFieldUint8 获取 FieldUint8
func (this *AllTypes) GetFieldUint8() uint8 {
	return this.FieldUint8
}

// SetFieldUint8 设置 FieldUint8
func (this *AllTypes) SetFieldUint8(FieldUint8 uint8) {
	this.FieldUint8 = FieldUint8
}

// GetFieldUint16 获取 FieldUint16
func (this *AllTypes) GetFieldUint16() uint16 {
	return this.FieldUint16
}

// SetFieldUint16 设置 FieldUint16
func (this *AllTypes) SetFieldUint16(FieldUint16 uint16) {
	this.FieldUint16 = FieldUint16
}

// GetFieldUint32 获取 FieldUint32
func (this *AllTypes) GetFieldUint32() uint32 {
	return this.FieldUint32
}

// SetFieldUint32 设置 FieldUint32
func (this *AllTypes) SetFieldUint32(FieldUint32 uint32) {
	this.FieldUint32 = FieldUint32
}

// GetFieldUint64 获取 FieldUint64
func (this *AllTypes) GetFieldUint64() uint64 {
	return this.FieldUint64
}

// SetFieldUint64 设置 FieldUint64
func (this *AllTypes) SetFieldUint64(FieldUint64 uint64) {
	this.FieldUint64 = FieldUint64
}

// GetFieldFloat32 获取 FieldFloat32
func (this *AllTypes) GetFieldFloat32() float32 {
	return this.FieldFloat32
}

// SetFieldFloat32 设置 FieldFloat32
func (this *AllTypes) SetFieldFloat32(FieldFloat32 float32) {
	this.FieldFloat32 = FieldFloat32
}

// GetFieldFloat64 获取 FieldFloat64
func (this *AllTypes) GetFieldFloat64() float64 {
	return this.FieldFloat64
}

// SetFieldFloat64 设置 FieldFloat64
func (this *AllTypes) SetFieldFloat64(FieldFloat64 float64) {
	this.FieldFloat64 = FieldFloat64
}

// GetFieldString 获取 FieldString
func (this *AllTypes) GetFieldString() string {
	return this.FieldString
}

// SetFieldString 设置 FieldString
func (this *AllTypes) SetFieldString(FieldString string) {
	this.FieldString = FieldString
}

// byte = uint8
// GetFieldByte 获取 FieldByte
func (this *AllTypes) GetFieldByte() byte {
	return this.FieldByte
}

// SetFieldByte 设置 FieldByte
func (this *AllTypes) SetFieldByte(FieldByte byte) {
	this.FieldByte = FieldByte
}

// rune = int32
// GetFieldRune 获取 FieldRune
func (this *AllTypes) GetFieldRune() rune {
	return this.FieldRune
}

// SetFieldRune 设置 FieldRune
func (this *AllTypes) SetFieldRune(FieldRune rune) {
	this.FieldRune = FieldRune
}

// --- 指针类型 ---
// GetFieldPtrInt 获取 FieldPtrInt
func (this *AllTypes) GetFieldPtrInt() *int {
	return this.FieldPtrInt
}

// SetFieldPtrInt 设置 FieldPtrInt
func (this *AllTypes) SetFieldPtrInt(FieldPtrInt *int) {
	this.FieldPtrInt = FieldPtrInt
}

// GetFieldPtrString 获取 FieldPtrString
func (this *AllTypes) GetFieldPtrString() *string {
	return this.FieldPtrString
}

// SetFieldPtrString 设置 FieldPtrString
func (this *AllTypes) SetFieldPtrString(FieldPtrString *string) {
	this.FieldPtrString = FieldPtrString
}

// GetFieldPtrStruct 获取 FieldPtrStruct
func (this *AllTypes) GetFieldPtrStruct() *BaseInfo {
	return this.FieldPtrStruct
}

// SetFieldPtrStruct 设置 FieldPtrStruct
func (this *AllTypes) SetFieldPtrStruct(FieldPtrStruct *BaseInfo) {
	this.FieldPtrStruct = FieldPtrStruct
}

// --- 具名类型（新类型） ---
// GetFieldUserID 获取 FieldUserID
func (this *AllTypes) GetFieldUserID() UserID {
	return this.FieldUserID
}

// SetFieldUserID 设置 FieldUserID
func (this *AllTypes) SetFieldUserID(FieldUserID UserID) {
	this.FieldUserID = FieldUserID
}

// GetFieldStatus 获取 FieldStatus
func (this *AllTypes) GetFieldStatus() Status {
	return this.FieldStatus
}

// SetFieldStatus 设置 FieldStatus
func (this *AllTypes) SetFieldStatus(FieldStatus Status) {
	this.FieldStatus = FieldStatus
}

// --- 类型别名 ---
// GetFieldMyTime 获取 FieldMyTime
func (this *AllTypes) GetFieldMyTime() MyTime {
	return this.FieldMyTime
}

// SetFieldMyTime 设置 FieldMyTime
func (this *AllTypes) SetFieldMyTime(FieldMyTime MyTime) {
	this.FieldMyTime = FieldMyTime
}

// --- 跨包具体类型 ---
// GetFieldTime 获取 FieldTime
func (this *AllTypes) GetFieldTime() time.Time {
	return this.FieldTime
}

// SetFieldTime 设置 FieldTime
func (this *AllTypes) SetFieldTime(FieldTime time.Time) {
	this.FieldTime = FieldTime
}

// GetFieldDuration 获取 FieldDuration
func (this *AllTypes) GetFieldDuration() time.Duration {
	return this.FieldDuration
}

// SetFieldDuration 设置 FieldDuration
func (this *AllTypes) SetFieldDuration(FieldDuration time.Duration) {
	this.FieldDuration = FieldDuration
}

// --- 切片类型 ---
// GetFieldSliceIntElem 获取切片 FieldSliceInt 中 index 位置的元素
func (this *AllTypes) GetFieldSliceIntElem(index int) int {
	return this.FieldSliceInt[index]
}

// GetFieldSliceIntLen 获取切片 FieldSliceInt 的长度
func (this *AllTypes) GetFieldSliceIntLen() int {
	return len(this.FieldSliceInt)
}

// GetFieldSliceIntCap 获取切片 FieldSliceInt 的容量
func (this *AllTypes) GetFieldSliceIntCap() int {
	return cap(this.FieldSliceInt)
}

// RangeFieldSliceInt 遍历切片 FieldSliceInt，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceInt(fn func(index int, value int) bool) {
	for i, v := range this.FieldSliceInt {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldSliceIntElem 设置切片 FieldSliceInt 中 index 位置的元素
func (this *AllTypes) SetFieldSliceIntElem(index int, elem int) {
	this.FieldSliceInt[index] = elem
}

// AddFieldSliceIntElem 向切片 FieldSliceInt 追加元素
func (this *AllTypes) AddFieldSliceIntElem(elem int) {
	this.FieldSliceInt = append(this.FieldSliceInt, elem)
}

// DelFieldSliceIntElem 删除切片 FieldSliceInt 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DelFieldSliceIntElem(index int) {
	this.FieldSliceInt = append(this.FieldSliceInt[:index], this.FieldSliceInt[index+1:]...)
}

// GetFieldSliceStringElem 获取切片 FieldSliceString 中 index 位置的元素
func (this *AllTypes) GetFieldSliceStringElem(index int) string {
	return this.FieldSliceString[index]
}

// GetFieldSliceStringLen 获取切片 FieldSliceString 的长度
func (this *AllTypes) GetFieldSliceStringLen() int {
	return len(this.FieldSliceString)
}

// GetFieldSliceStringCap 获取切片 FieldSliceString 的容量
func (this *AllTypes) GetFieldSliceStringCap() int {
	return cap(this.FieldSliceString)
}

// RangeFieldSliceString 遍历切片 FieldSliceString，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceString(fn func(index int, value string) bool) {
	for i, v := range this.FieldSliceString {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldSliceStringElem 设置切片 FieldSliceString 中 index 位置的元素
func (this *AllTypes) SetFieldSliceStringElem(index int, elem string) {
	this.FieldSliceString[index] = elem
}

// AddFieldSliceStringElem 向切片 FieldSliceString 追加元素
func (this *AllTypes) AddFieldSliceStringElem(elem string) {
	this.FieldSliceString = append(this.FieldSliceString, elem)
}

// DelFieldSliceStringElem 删除切片 FieldSliceString 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DelFieldSliceStringElem(index int) {
	this.FieldSliceString = append(this.FieldSliceString[:index], this.FieldSliceString[index+1:]...)
}

// GetFieldSliceStructElem 获取切片 FieldSliceStruct 中 index 位置的元素
func (this *AllTypes) GetFieldSliceStructElem(index int) *BaseInfo {
	return this.FieldSliceStruct[index]
}

// GetFieldSliceStructLen 获取切片 FieldSliceStruct 的长度
func (this *AllTypes) GetFieldSliceStructLen() int {
	return len(this.FieldSliceStruct)
}

// GetFieldSliceStructCap 获取切片 FieldSliceStruct 的容量
func (this *AllTypes) GetFieldSliceStructCap() int {
	return cap(this.FieldSliceStruct)
}

// RangeFieldSliceStruct 遍历切片 FieldSliceStruct，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceStruct(fn func(index int, value *BaseInfo) bool) {
	for i, v := range this.FieldSliceStruct {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldSliceStructElem 设置切片 FieldSliceStruct 中 index 位置的元素
func (this *AllTypes) SetFieldSliceStructElem(index int, elem *BaseInfo) {
	this.FieldSliceStruct[index] = elem
}

// AddFieldSliceStructElem 向切片 FieldSliceStruct 追加元素
func (this *AllTypes) AddFieldSliceStructElem(elem *BaseInfo) {
	this.FieldSliceStruct = append(this.FieldSliceStruct, elem)
}

// DelFieldSliceStructElem 删除切片 FieldSliceStruct 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DelFieldSliceStructElem(index int) {
	this.FieldSliceStruct = append(this.FieldSliceStruct[:index], this.FieldSliceStruct[index+1:]...)
}

// 具名切片类型
// GetFieldTagsElem 获取切片 FieldTags 中 index 位置的元素
func (this *AllTypes) GetFieldTagsElem(index int) string {
	return this.FieldTags[index]
}

// GetFieldTagsLen 获取切片 FieldTags 的长度
func (this *AllTypes) GetFieldTagsLen() int {
	return len(this.FieldTags)
}

// GetFieldTagsCap 获取切片 FieldTags 的容量
func (this *AllTypes) GetFieldTagsCap() int {
	return cap(this.FieldTags)
}

// RangeFieldTags 遍历切片 FieldTags，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldTags(fn func(index int, value string) bool) {
	for i, v := range this.FieldTags {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldTagsElem 设置切片 FieldTags 中 index 位置的元素
func (this *AllTypes) SetFieldTagsElem(index int, elem string) {
	this.FieldTags[index] = elem
}

// AddFieldTagsElem 向切片 FieldTags 追加元素
func (this *AllTypes) AddFieldTagsElem(elem string) {
	this.FieldTags = append(this.FieldTags, elem)
}

// DelFieldTagsElem 删除切片 FieldTags 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DelFieldTagsElem(index int) {
	this.FieldTags = append(this.FieldTags[:index], this.FieldTags[index+1:]...)
}

// --- 数组类型（固定长度）---
// GetFieldArray8Elem 获取数组 FieldArray8 中 index 位置的元素
func (this *AllTypes) GetFieldArray8Elem(index int) int {
	return this.FieldArray8[index]
}

// GetFieldArray8Len 获取数组 FieldArray8 的长度
func (this *AllTypes) GetFieldArray8Len() int {
	return len(this.FieldArray8)
}

// RangeFieldArray8 遍历数组 FieldArray8，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldArray8(fn func(index int, value int) bool) {
	for i, v := range this.FieldArray8 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldArray8Elem 设置数组 FieldArray8 中 index 位置的元素
func (this *AllTypes) SetFieldArray8Elem(index int, elem int) {
	this.FieldArray8[index] = elem
}

// GetFieldArrayStrElem 获取数组 FieldArrayStr 中 index 位置的元素
func (this *AllTypes) GetFieldArrayStrElem(index int) string {
	return this.FieldArrayStr[index]
}

// GetFieldArrayStrLen 获取数组 FieldArrayStr 的长度
func (this *AllTypes) GetFieldArrayStrLen() int {
	return len(this.FieldArrayStr)
}

// RangeFieldArrayStr 遍历数组 FieldArrayStr，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldArrayStr(fn func(index int, value string) bool) {
	for i, v := range this.FieldArrayStr {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldArrayStrElem 设置数组 FieldArrayStr 中 index 位置的元素
func (this *AllTypes) SetFieldArrayStrElem(index int, elem string) {
	this.FieldArrayStr[index] = elem
}

// --- Map 类型 ---
// GetFieldMapStrIntVal 获取 FieldMapStrInt 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMapStrIntVal(key string) (int, bool) {
	val, ok := this.FieldMapStrInt[key]
	return val, ok
}

// RangeFieldMapStrInt 遍历 FieldMapStrInt，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMapStrInt(fn func(key string, value int) bool) {
	for k, v := range this.FieldMapStrInt {
		if !fn(k, v) {
			break
		}
	}
}

// SetFieldMapStrIntKV 设置 FieldMapStrInt 中指定 key 的值
func (this *AllTypes) SetFieldMapStrIntKV(key string, value int) {
	this.FieldMapStrInt[key] = value
}

// DelFieldMapStrIntKV 删除 FieldMapStrInt 中指定 key
func (this *AllTypes) DelFieldMapStrIntKV(key string) {
	delete(this.FieldMapStrInt, key)
}

// GetFieldMapStrStructVal 获取 FieldMapStrStruct 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMapStrStructVal(key string) (*BaseInfo, bool) {
	val, ok := this.FieldMapStrStruct[key]
	return val, ok
}

// RangeFieldMapStrStruct 遍历 FieldMapStrStruct，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMapStrStruct(fn func(key string, value *BaseInfo) bool) {
	for k, v := range this.FieldMapStrStruct {
		if !fn(k, v) {
			break
		}
	}
}

// SetFieldMapStrStructKV 设置 FieldMapStrStruct 中指定 key 的值
func (this *AllTypes) SetFieldMapStrStructKV(key string, value *BaseInfo) {
	this.FieldMapStrStruct[key] = value
}

// DelFieldMapStrStructKV 删除 FieldMapStrStruct 中指定 key
func (this *AllTypes) DelFieldMapStrStructKV(key string) {
	delete(this.FieldMapStrStruct, key)
}

// 具名 map 类型
// GetFieldMetadataVal 获取 FieldMetadata 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMetadataVal(key string) (string, bool) {
	val, ok := this.FieldMetadata[key]
	return val, ok
}

// RangeFieldMetadata 遍历 FieldMetadata，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMetadata(fn func(key string, value string) bool) {
	for k, v := range this.FieldMetadata {
		if !fn(k, v) {
			break
		}
	}
}

// SetFieldMetadataKV 设置 FieldMetadata 中指定 key 的值
func (this *AllTypes) SetFieldMetadataKV(key string, value string) {
	this.FieldMetadata[key] = value
}

// DelFieldMetadataKV 删除 FieldMetadata 中指定 key
func (this *AllTypes) DelFieldMetadataKV(key string) {
	delete(this.FieldMetadata, key)
}

// --- 嵌套复合类型 ---
// GetFieldMapSliceVal 获取 FieldMapSlice 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMapSliceVal(key string) ([]string, bool) {
	val, ok := this.FieldMapSlice[key]
	return val, ok
}

// RangeFieldMapSlice 遍历 FieldMapSlice，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMapSlice(fn func(key string, value []string) bool) {
	for k, v := range this.FieldMapSlice {
		if !fn(k, v) {
			break
		}
	}
}

// SetFieldMapSliceKV 设置 FieldMapSlice 中指定 key 的值
func (this *AllTypes) SetFieldMapSliceKV(key string, value []string) {
	this.FieldMapSlice[key] = value
}

// DelFieldMapSliceKV 删除 FieldMapSlice 中指定 key
func (this *AllTypes) DelFieldMapSliceKV(key string) {
	delete(this.FieldMapSlice, key)
}

// slice elem 是 map
// GetFieldSliceMapElem 获取切片 FieldSliceMap 中 index 位置的元素
func (this *AllTypes) GetFieldSliceMapElem(index int) map[string]int {
	return this.FieldSliceMap[index]
}

// GetFieldSliceMapLen 获取切片 FieldSliceMap 的长度
func (this *AllTypes) GetFieldSliceMapLen() int {
	return len(this.FieldSliceMap)
}

// GetFieldSliceMapCap 获取切片 FieldSliceMap 的容量
func (this *AllTypes) GetFieldSliceMapCap() int {
	return cap(this.FieldSliceMap)
}

// RangeFieldSliceMap 遍历切片 FieldSliceMap，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceMap(fn func(index int, value map[string]int) bool) {
	for i, v := range this.FieldSliceMap {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldSliceMapElem 设置切片 FieldSliceMap 中 index 位置的元素
func (this *AllTypes) SetFieldSliceMapElem(index int, elem map[string]int) {
	this.FieldSliceMap[index] = elem
}

// AddFieldSliceMapElem 向切片 FieldSliceMap 追加元素
func (this *AllTypes) AddFieldSliceMapElem(elem map[string]int) {
	this.FieldSliceMap = append(this.FieldSliceMap, elem)
}

// DelFieldSliceMapElem 删除切片 FieldSliceMap 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DelFieldSliceMapElem(index int) {
	this.FieldSliceMap = append(this.FieldSliceMap[:index], this.FieldSliceMap[index+1:]...)
}

// 只生成 getter
// GetFieldReadonly 获取 FieldReadonly
func (this *AllTypes) GetFieldReadonly() string {
	return this.FieldReadonly
}

// 只生成 setter
// SetFieldWriteOnly 设置 FieldWriteOnly
func (this *AllTypes) SetFieldWriteOnly(FieldWriteOnly string) {
	this.FieldWriteOnly = FieldWriteOnly
}

// 多个 tag 共存
// GetFieldWithJSON 获取 FieldWithJSON
func (this *AllTypes) GetFieldWithJSON() string {
	return this.FieldWithJSON
}

// --- interface / func 类型：生成 Get/Set ---
// GetFieldInterface 获取 FieldInterface
func (this *AllTypes) GetFieldInterface() interface{} {
	return this.FieldInterface
}

// SetFieldInterface 设置 FieldInterface
func (this *AllTypes) SetFieldInterface(FieldInterface interface{}) {
	this.FieldInterface = FieldInterface
}

// 生成 GetFieldFunc/SetFieldFunc
// GetFieldFunc 获取 FieldFunc
func (this *AllTypes) GetFieldFunc() func(int) string {
	return this.FieldFunc
}

// SetFieldFunc 设置 FieldFunc
func (this *AllTypes) SetFieldFunc(FieldFunc func(int) string) {
	this.FieldFunc = FieldFunc
}

// 生成 GetFieldAny/SetFieldAny（any = interface{}）
// GetFieldAny 获取 FieldAny
func (this *AllTypes) GetFieldAny() any {
	return this.FieldAny
}

// SetFieldAny 设置 FieldAny
func (this *AllTypes) SetFieldAny(FieldAny any) {
	this.FieldAny = FieldAny
}
