// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import (
	"maps"
	"slices"
	"time"
)

// --- 基础类型 ---
// GetFieldBool 获取 FieldBool
func (this *AllTypes) GetFieldBool() bool {
	return this.FieldBool
}

// SetFieldBool 设置 FieldBool
func (this *AllTypes) SetFieldBool(FieldBool bool) {
	this.FieldBool = FieldBool
}

// ToggleFieldBool 翻转 FieldBool 的布尔值
func (this *AllTypes) ToggleFieldBool() {
	this.FieldBool = !this.FieldBool
}

// GetFieldInt 获取 FieldInt
func (this *AllTypes) GetFieldInt() int {
	return this.FieldInt
}

// SetFieldInt 设置 FieldInt
func (this *AllTypes) SetFieldInt(FieldInt int) {
	this.FieldInt = FieldInt
}

// AddFieldInt 将 FieldInt 增加 delta
func (this *AllTypes) AddFieldInt(delta int) {
	this.FieldInt += delta
}

// SubFieldInt 将 FieldInt 减少 delta
func (this *AllTypes) SubFieldInt(delta int) {
	this.FieldInt -= delta
}

// GetFieldInt8 获取 FieldInt8
func (this *AllTypes) GetFieldInt8() int8 {
	return this.FieldInt8
}

// SetFieldInt8 设置 FieldInt8
func (this *AllTypes) SetFieldInt8(FieldInt8 int8) {
	this.FieldInt8 = FieldInt8
}

// AddFieldInt8 将 FieldInt8 增加 delta
func (this *AllTypes) AddFieldInt8(delta int8) {
	this.FieldInt8 += delta
}

// SubFieldInt8 将 FieldInt8 减少 delta
func (this *AllTypes) SubFieldInt8(delta int8) {
	this.FieldInt8 -= delta
}

// GetFieldInt16 获取 FieldInt16
func (this *AllTypes) GetFieldInt16() int16 {
	return this.FieldInt16
}

// SetFieldInt16 设置 FieldInt16
func (this *AllTypes) SetFieldInt16(FieldInt16 int16) {
	this.FieldInt16 = FieldInt16
}

// AddFieldInt16 将 FieldInt16 增加 delta
func (this *AllTypes) AddFieldInt16(delta int16) {
	this.FieldInt16 += delta
}

// SubFieldInt16 将 FieldInt16 减少 delta
func (this *AllTypes) SubFieldInt16(delta int16) {
	this.FieldInt16 -= delta
}

// GetFieldInt32 获取 FieldInt32
func (this *AllTypes) GetFieldInt32() int32 {
	return this.FieldInt32
}

// SetFieldInt32 设置 FieldInt32
func (this *AllTypes) SetFieldInt32(FieldInt32 int32) {
	this.FieldInt32 = FieldInt32
}

// AddFieldInt32 将 FieldInt32 增加 delta
func (this *AllTypes) AddFieldInt32(delta int32) {
	this.FieldInt32 += delta
}

// SubFieldInt32 将 FieldInt32 减少 delta
func (this *AllTypes) SubFieldInt32(delta int32) {
	this.FieldInt32 -= delta
}

// GetFieldInt64 获取 FieldInt64
func (this *AllTypes) GetFieldInt64() int64 {
	return this.FieldInt64
}

// SetFieldInt64 设置 FieldInt64
func (this *AllTypes) SetFieldInt64(FieldInt64 int64) {
	this.FieldInt64 = FieldInt64
}

// AddFieldInt64 将 FieldInt64 增加 delta
func (this *AllTypes) AddFieldInt64(delta int64) {
	this.FieldInt64 += delta
}

// SubFieldInt64 将 FieldInt64 减少 delta
func (this *AllTypes) SubFieldInt64(delta int64) {
	this.FieldInt64 -= delta
}

// GetFieldUint 获取 FieldUint
func (this *AllTypes) GetFieldUint() uint {
	return this.FieldUint
}

// SetFieldUint 设置 FieldUint
func (this *AllTypes) SetFieldUint(FieldUint uint) {
	this.FieldUint = FieldUint
}

// AddFieldUint 将 FieldUint 增加 delta
func (this *AllTypes) AddFieldUint(delta uint) {
	this.FieldUint += delta
}

// SubFieldUint 将 FieldUint 减少 delta
func (this *AllTypes) SubFieldUint(delta uint) {
	this.FieldUint -= delta
}

// GetFieldUint8 获取 FieldUint8
func (this *AllTypes) GetFieldUint8() uint8 {
	return this.FieldUint8
}

// SetFieldUint8 设置 FieldUint8
func (this *AllTypes) SetFieldUint8(FieldUint8 uint8) {
	this.FieldUint8 = FieldUint8
}

// AddFieldUint8 将 FieldUint8 增加 delta
func (this *AllTypes) AddFieldUint8(delta uint8) {
	this.FieldUint8 += delta
}

// SubFieldUint8 将 FieldUint8 减少 delta
func (this *AllTypes) SubFieldUint8(delta uint8) {
	this.FieldUint8 -= delta
}

// GetFieldUint16 获取 FieldUint16
func (this *AllTypes) GetFieldUint16() uint16 {
	return this.FieldUint16
}

// SetFieldUint16 设置 FieldUint16
func (this *AllTypes) SetFieldUint16(FieldUint16 uint16) {
	this.FieldUint16 = FieldUint16
}

// AddFieldUint16 将 FieldUint16 增加 delta
func (this *AllTypes) AddFieldUint16(delta uint16) {
	this.FieldUint16 += delta
}

// SubFieldUint16 将 FieldUint16 减少 delta
func (this *AllTypes) SubFieldUint16(delta uint16) {
	this.FieldUint16 -= delta
}

// GetFieldUint32 获取 FieldUint32
func (this *AllTypes) GetFieldUint32() uint32 {
	return this.FieldUint32
}

// SetFieldUint32 设置 FieldUint32
func (this *AllTypes) SetFieldUint32(FieldUint32 uint32) {
	this.FieldUint32 = FieldUint32
}

// AddFieldUint32 将 FieldUint32 增加 delta
func (this *AllTypes) AddFieldUint32(delta uint32) {
	this.FieldUint32 += delta
}

// SubFieldUint32 将 FieldUint32 减少 delta
func (this *AllTypes) SubFieldUint32(delta uint32) {
	this.FieldUint32 -= delta
}

// GetFieldUint64 获取 FieldUint64
func (this *AllTypes) GetFieldUint64() uint64 {
	return this.FieldUint64
}

// SetFieldUint64 设置 FieldUint64
func (this *AllTypes) SetFieldUint64(FieldUint64 uint64) {
	this.FieldUint64 = FieldUint64
}

// AddFieldUint64 将 FieldUint64 增加 delta
func (this *AllTypes) AddFieldUint64(delta uint64) {
	this.FieldUint64 += delta
}

// SubFieldUint64 将 FieldUint64 减少 delta
func (this *AllTypes) SubFieldUint64(delta uint64) {
	this.FieldUint64 -= delta
}

// GetFieldFloat32 获取 FieldFloat32
func (this *AllTypes) GetFieldFloat32() float32 {
	return this.FieldFloat32
}

// SetFieldFloat32 设置 FieldFloat32
func (this *AllTypes) SetFieldFloat32(FieldFloat32 float32) {
	this.FieldFloat32 = FieldFloat32
}

// AddFieldFloat32 将 FieldFloat32 增加 delta
func (this *AllTypes) AddFieldFloat32(delta float32) {
	this.FieldFloat32 += delta
}

// SubFieldFloat32 将 FieldFloat32 减少 delta
func (this *AllTypes) SubFieldFloat32(delta float32) {
	this.FieldFloat32 -= delta
}

// GetFieldFloat64 获取 FieldFloat64
func (this *AllTypes) GetFieldFloat64() float64 {
	return this.FieldFloat64
}

// SetFieldFloat64 设置 FieldFloat64
func (this *AllTypes) SetFieldFloat64(FieldFloat64 float64) {
	this.FieldFloat64 = FieldFloat64
}

// AddFieldFloat64 将 FieldFloat64 增加 delta
func (this *AllTypes) AddFieldFloat64(delta float64) {
	this.FieldFloat64 += delta
}

// SubFieldFloat64 将 FieldFloat64 减少 delta
func (this *AllTypes) SubFieldFloat64(delta float64) {
	this.FieldFloat64 -= delta
}

// GetFieldString 获取 FieldString
func (this *AllTypes) GetFieldString() string {
	return this.FieldString
}

// SetFieldString 设置 FieldString
func (this *AllTypes) SetFieldString(FieldString string) {
	this.FieldString = FieldString
}

// byte = uint8
// GetFieldByte 获取 FieldByte
func (this *AllTypes) GetFieldByte() byte {
	return this.FieldByte
}

// SetFieldByte 设置 FieldByte
func (this *AllTypes) SetFieldByte(FieldByte byte) {
	this.FieldByte = FieldByte
}

// AddFieldByte 将 FieldByte 增加 delta
func (this *AllTypes) AddFieldByte(delta byte) {
	this.FieldByte += delta
}

// SubFieldByte 将 FieldByte 减少 delta
func (this *AllTypes) SubFieldByte(delta byte) {
	this.FieldByte -= delta
}

// rune = int32
// GetFieldRune 获取 FieldRune
func (this *AllTypes) GetFieldRune() rune {
	return this.FieldRune
}

// SetFieldRune 设置 FieldRune
func (this *AllTypes) SetFieldRune(FieldRune rune) {
	this.FieldRune = FieldRune
}

// AddFieldRune 将 FieldRune 增加 delta
func (this *AllTypes) AddFieldRune(delta rune) {
	this.FieldRune += delta
}

// SubFieldRune 将 FieldRune 减少 delta
func (this *AllTypes) SubFieldRune(delta rune) {
	this.FieldRune -= delta
}

// --- 指针类型 ---
// GetFieldPtrInt 获取 FieldPtrInt
func (this *AllTypes) GetFieldPtrInt() *int {
	return this.FieldPtrInt
}

// SetFieldPtrInt 设置 FieldPtrInt
func (this *AllTypes) SetFieldPtrInt(FieldPtrInt *int) {
	this.FieldPtrInt = FieldPtrInt
}

// HasFieldPtrInt 返回 FieldPtrInt 是否已初始化（非 nil）
func (this *AllTypes) HasFieldPtrInt() bool {
	return this.FieldPtrInt != nil
}

// GetFieldPtrString 获取 FieldPtrString
func (this *AllTypes) GetFieldPtrString() *string {
	return this.FieldPtrString
}

// SetFieldPtrString 设置 FieldPtrString
func (this *AllTypes) SetFieldPtrString(FieldPtrString *string) {
	this.FieldPtrString = FieldPtrString
}

// HasFieldPtrString 返回 FieldPtrString 是否已初始化（非 nil）
func (this *AllTypes) HasFieldPtrString() bool {
	return this.FieldPtrString != nil
}

// GetFieldPtrStruct 获取 FieldPtrStruct
func (this *AllTypes) GetFieldPtrStruct() *BaseInfo {
	return this.FieldPtrStruct
}

// SetFieldPtrStruct 设置 FieldPtrStruct
func (this *AllTypes) SetFieldPtrStruct(FieldPtrStruct *BaseInfo) {
	this.FieldPtrStruct = FieldPtrStruct
}

// HasFieldPtrStruct 返回 FieldPtrStruct 是否已初始化（非 nil）
func (this *AllTypes) HasFieldPtrStruct() bool {
	return this.FieldPtrStruct != nil
}

// --- 具名类型（新类型） ---
// GetFieldUserID 获取 FieldUserID
func (this *AllTypes) GetFieldUserID() UserID {
	return this.FieldUserID
}

// SetFieldUserID 设置 FieldUserID
func (this *AllTypes) SetFieldUserID(FieldUserID UserID) {
	this.FieldUserID = FieldUserID
}

// AddFieldUserID 将 FieldUserID 增加 delta
func (this *AllTypes) AddFieldUserID(delta UserID) {
	this.FieldUserID += delta
}

// SubFieldUserID 将 FieldUserID 减少 delta
func (this *AllTypes) SubFieldUserID(delta UserID) {
	this.FieldUserID -= delta
}

// GetFieldStatus 获取 FieldStatus
func (this *AllTypes) GetFieldStatus() Status {
	return this.FieldStatus
}

// SetFieldStatus 设置 FieldStatus
func (this *AllTypes) SetFieldStatus(FieldStatus Status) {
	this.FieldStatus = FieldStatus
}

// --- 类型别名 ---
// GetFieldMyTime 获取 FieldMyTime
func (this *AllTypes) GetFieldMyTime() MyTime {
	return this.FieldMyTime
}

// SetFieldMyTime 设置 FieldMyTime
func (this *AllTypes) SetFieldMyTime(FieldMyTime MyTime) {
	this.FieldMyTime = FieldMyTime
}

// --- 跨包具体类型 ---
// GetFieldTime 获取 FieldTime
func (this *AllTypes) GetFieldTime() time.Time {
	return this.FieldTime
}

// SetFieldTime 设置 FieldTime
func (this *AllTypes) SetFieldTime(FieldTime time.Time) {
	this.FieldTime = FieldTime
}

// GetFieldDuration 获取 FieldDuration
func (this *AllTypes) GetFieldDuration() time.Duration {
	return this.FieldDuration
}

// SetFieldDuration 设置 FieldDuration
func (this *AllTypes) SetFieldDuration(FieldDuration time.Duration) {
	this.FieldDuration = FieldDuration
}

// AddFieldDuration 将 FieldDuration 增加 delta
func (this *AllTypes) AddFieldDuration(delta time.Duration) {
	this.FieldDuration += delta
}

// SubFieldDuration 将 FieldDuration 减少 delta
func (this *AllTypes) SubFieldDuration(delta time.Duration) {
	this.FieldDuration -= delta
}

// --- 切片类型 ---
// GetFieldSliceIntAt 获取切片 FieldSliceInt 中 index 位置的元素
func (this *AllTypes) GetFieldSliceIntAt(index int) int {
	return this.FieldSliceInt[index]
}

// GetFieldSliceIntLen 获取切片 FieldSliceInt 的长度
func (this *AllTypes) GetFieldSliceIntLen() int {
	return len(this.FieldSliceInt)
}

// RangeFieldSliceInt 遍历切片 FieldSliceInt，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceInt(fn func(index int, value int) bool) {
	for i, v := range this.FieldSliceInt {
		if !fn(i, v) {
			break
		}
	}
}

// HasFieldSliceInt 返回切片 FieldSliceInt 是否已初始化（非 nil）
func (this *AllTypes) HasFieldSliceInt() bool {
	return this.FieldSliceInt != nil
}

// GetFieldSliceIntCopy 返回切片 FieldSliceInt 的浅拷贝
func (this *AllTypes) GetFieldSliceIntCopy() []int {
	return slices.Clone(this.FieldSliceInt)
}

// SetFieldSliceIntAt 设置切片 FieldSliceInt 中 index 位置的元素
func (this *AllTypes) SetFieldSliceIntAt(index int, elem int) {
	this.FieldSliceInt[index] = elem
}

// AppendFieldSliceInt 向切片 FieldSliceInt 追加一个或多个元素
func (this *AllTypes) AppendFieldSliceInt(elems ...int) {
	this.FieldSliceInt = append(this.FieldSliceInt, elems...)
}

// DeleteFieldSliceIntAt 删除切片 FieldSliceInt 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DeleteFieldSliceIntAt(index int) {
	this.FieldSliceInt = slices.Delete(this.FieldSliceInt, index, index+1)
}

// GetFieldSliceStringAt 获取切片 FieldSliceString 中 index 位置的元素
func (this *AllTypes) GetFieldSliceStringAt(index int) string {
	return this.FieldSliceString[index]
}

// GetFieldSliceStringLen 获取切片 FieldSliceString 的长度
func (this *AllTypes) GetFieldSliceStringLen() int {
	return len(this.FieldSliceString)
}

// RangeFieldSliceString 遍历切片 FieldSliceString，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceString(fn func(index int, value string) bool) {
	for i, v := range this.FieldSliceString {
		if !fn(i, v) {
			break
		}
	}
}

// HasFieldSliceString 返回切片 FieldSliceString 是否已初始化（非 nil）
func (this *AllTypes) HasFieldSliceString() bool {
	return this.FieldSliceString != nil
}

// GetFieldSliceStringCopy 返回切片 FieldSliceString 的浅拷贝
func (this *AllTypes) GetFieldSliceStringCopy() []string {
	return slices.Clone(this.FieldSliceString)
}

// SetFieldSliceStringAt 设置切片 FieldSliceString 中 index 位置的元素
func (this *AllTypes) SetFieldSliceStringAt(index int, elem string) {
	this.FieldSliceString[index] = elem
}

// AppendFieldSliceString 向切片 FieldSliceString 追加一个或多个元素
func (this *AllTypes) AppendFieldSliceString(elems ...string) {
	this.FieldSliceString = append(this.FieldSliceString, elems...)
}

// DeleteFieldSliceStringAt 删除切片 FieldSliceString 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DeleteFieldSliceStringAt(index int) {
	this.FieldSliceString = slices.Delete(this.FieldSliceString, index, index+1)
}

// GetFieldSliceStructAt 获取切片 FieldSliceStruct 中 index 位置的元素
func (this *AllTypes) GetFieldSliceStructAt(index int) *BaseInfo {
	return this.FieldSliceStruct[index]
}

// GetFieldSliceStructLen 获取切片 FieldSliceStruct 的长度
func (this *AllTypes) GetFieldSliceStructLen() int {
	return len(this.FieldSliceStruct)
}

// RangeFieldSliceStruct 遍历切片 FieldSliceStruct，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceStruct(fn func(index int, value *BaseInfo) bool) {
	for i, v := range this.FieldSliceStruct {
		if !fn(i, v) {
			break
		}
	}
}

// HasFieldSliceStruct 返回切片 FieldSliceStruct 是否已初始化（非 nil）
func (this *AllTypes) HasFieldSliceStruct() bool {
	return this.FieldSliceStruct != nil
}

// GetFieldSliceStructCopy 返回切片 FieldSliceStruct 的浅拷贝
func (this *AllTypes) GetFieldSliceStructCopy() []*BaseInfo {
	return slices.Clone(this.FieldSliceStruct)
}

// SetFieldSliceStructAt 设置切片 FieldSliceStruct 中 index 位置的元素
func (this *AllTypes) SetFieldSliceStructAt(index int, elem *BaseInfo) {
	this.FieldSliceStruct[index] = elem
}

// AppendFieldSliceStruct 向切片 FieldSliceStruct 追加一个或多个元素
func (this *AllTypes) AppendFieldSliceStruct(elems ...*BaseInfo) {
	this.FieldSliceStruct = append(this.FieldSliceStruct, elems...)
}

// DeleteFieldSliceStructAt 删除切片 FieldSliceStruct 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DeleteFieldSliceStructAt(index int) {
	this.FieldSliceStruct = slices.Delete(this.FieldSliceStruct, index, index+1)
}

// 具名切片类型
// GetFieldTagsAt 获取切片 FieldTags 中 index 位置的元素
func (this *AllTypes) GetFieldTagsAt(index int) string {
	return this.FieldTags[index]
}

// GetFieldTagsLen 获取切片 FieldTags 的长度
func (this *AllTypes) GetFieldTagsLen() int {
	return len(this.FieldTags)
}

// RangeFieldTags 遍历切片 FieldTags，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldTags(fn func(index int, value string) bool) {
	for i, v := range this.FieldTags {
		if !fn(i, v) {
			break
		}
	}
}

// HasFieldTags 返回切片 FieldTags 是否已初始化（非 nil）
func (this *AllTypes) HasFieldTags() bool {
	return this.FieldTags != nil
}

// GetFieldTagsCopy 返回切片 FieldTags 的浅拷贝
func (this *AllTypes) GetFieldTagsCopy() Tags {
	return slices.Clone(this.FieldTags)
}

// SetFieldTagsAt 设置切片 FieldTags 中 index 位置的元素
func (this *AllTypes) SetFieldTagsAt(index int, elem string) {
	this.FieldTags[index] = elem
}

// AppendFieldTags 向切片 FieldTags 追加一个或多个元素
func (this *AllTypes) AppendFieldTags(elems ...string) {
	this.FieldTags = append(this.FieldTags, elems...)
}

// DeleteFieldTagsAt 删除切片 FieldTags 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DeleteFieldTagsAt(index int) {
	this.FieldTags = slices.Delete(this.FieldTags, index, index+1)
}

// --- 数组类型（固定长度）---
// GetFieldArray8 获取数组 FieldArray8 的完整副本
func (this *AllTypes) GetFieldArray8() [8]int {
	return this.FieldArray8
}

// GetFieldArray8At 获取数组 FieldArray8 中 index 位置的元素
func (this *AllTypes) GetFieldArray8At(index int) int {
	return this.FieldArray8[index]
}

// GetFieldArray8Len 获取数组 FieldArray8 的长度
func (this *AllTypes) GetFieldArray8Len() int {
	return len(this.FieldArray8)
}

// RangeFieldArray8 遍历数组 FieldArray8，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldArray8(fn func(index int, value int) bool) {
	for i, v := range this.FieldArray8 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldArray8At 设置数组 FieldArray8 中 index 位置的元素
func (this *AllTypes) SetFieldArray8At(index int, elem int) {
	this.FieldArray8[index] = elem
}

// GetFieldArrayStr 获取数组 FieldArrayStr 的完整副本
func (this *AllTypes) GetFieldArrayStr() [4]string {
	return this.FieldArrayStr
}

// GetFieldArrayStrAt 获取数组 FieldArrayStr 中 index 位置的元素
func (this *AllTypes) GetFieldArrayStrAt(index int) string {
	return this.FieldArrayStr[index]
}

// GetFieldArrayStrLen 获取数组 FieldArrayStr 的长度
func (this *AllTypes) GetFieldArrayStrLen() int {
	return len(this.FieldArrayStr)
}

// RangeFieldArrayStr 遍历数组 FieldArrayStr，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldArrayStr(fn func(index int, value string) bool) {
	for i, v := range this.FieldArrayStr {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldArrayStrAt 设置数组 FieldArrayStr 中 index 位置的元素
func (this *AllTypes) SetFieldArrayStrAt(index int, elem string) {
	this.FieldArrayStr[index] = elem
}

// --- Map 类型 ---
// GetFieldMapStrIntVal 获取 FieldMapStrInt 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMapStrIntVal(key string) (int, bool) {
	val, ok := this.FieldMapStrInt[key]
	return val, ok
}

// GetFieldMapStrIntValOrDefault 获取 FieldMapStrInt 中指定 key 的值，key 不存在时返回 def
func (this *AllTypes) GetFieldMapStrIntValOrDefault(key string, def int) int {
	if val, ok := this.FieldMapStrInt[key]; ok {
		return val
	}
	return def
}

// RangeFieldMapStrInt 遍历 FieldMapStrInt，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMapStrInt(fn func(key string, value int) bool) {
	for k, v := range this.FieldMapStrInt {
		if !fn(k, v) {
			break
		}
	}
}

// HasFieldMapStrInt 返回 FieldMapStrInt 是否已初始化（非 nil）
func (this *AllTypes) HasFieldMapStrInt() bool {
	return this.FieldMapStrInt != nil
}

// HasFieldMapStrIntKey 检查 FieldMapStrInt 中指定 key 是否存在
func (this *AllTypes) HasFieldMapStrIntKey(key string) bool {
	_, ok := this.FieldMapStrInt[key]
	return ok
}

// GetFieldMapStrIntLen 获取 FieldMapStrInt 的元素数量
func (this *AllTypes) GetFieldMapStrIntLen() int {
	return len(this.FieldMapStrInt)
}

// GetFieldMapStrIntKeys 返回 FieldMapStrInt 中所有 key 的切片（顺序不确定）
func (this *AllTypes) GetFieldMapStrIntKeys() []string {
	keys := make([]string, 0, len(this.FieldMapStrInt))
	for k := range this.FieldMapStrInt {
		keys = append(keys, k)
	}
	return keys
}

// GetFieldMapStrIntCopy 返回 FieldMapStrInt 的浅拷贝
func (this *AllTypes) GetFieldMapStrIntCopy() map[string]int {
	return maps.Clone(this.FieldMapStrInt)
}

// EnsureFieldMapStrInt 确保 FieldMapStrInt 已初始化（nil 时自动创建空 map），返回字段引用
func (this *AllTypes) EnsureFieldMapStrInt() map[string]int {
	if this.FieldMapStrInt == nil {
		this.FieldMapStrInt = make(map[string]int)
	}
	return this.FieldMapStrInt
}

// SetFieldMapStrIntVal 设置 FieldMapStrInt 中指定 key 的值
func (this *AllTypes) SetFieldMapStrIntVal(key string, value int) {
	this.FieldMapStrInt[key] = value
}

// DeleteFieldMapStrIntKey 删除 FieldMapStrInt 中指定 key
func (this *AllTypes) DeleteFieldMapStrIntKey(key string) {
	delete(this.FieldMapStrInt, key)
}

// GetFieldMapStrStructVal 获取 FieldMapStrStruct 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMapStrStructVal(key string) (*BaseInfo, bool) {
	val, ok := this.FieldMapStrStruct[key]
	return val, ok
}

// GetFieldMapStrStructValOrDefault 获取 FieldMapStrStruct 中指定 key 的值，key 不存在时返回 def
func (this *AllTypes) GetFieldMapStrStructValOrDefault(key string, def *BaseInfo) *BaseInfo {
	if val, ok := this.FieldMapStrStruct[key]; ok {
		return val
	}
	return def
}

// RangeFieldMapStrStruct 遍历 FieldMapStrStruct，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMapStrStruct(fn func(key string, value *BaseInfo) bool) {
	for k, v := range this.FieldMapStrStruct {
		if !fn(k, v) {
			break
		}
	}
}

// HasFieldMapStrStruct 返回 FieldMapStrStruct 是否已初始化（非 nil）
func (this *AllTypes) HasFieldMapStrStruct() bool {
	return this.FieldMapStrStruct != nil
}

// HasFieldMapStrStructKey 检查 FieldMapStrStruct 中指定 key 是否存在
func (this *AllTypes) HasFieldMapStrStructKey(key string) bool {
	_, ok := this.FieldMapStrStruct[key]
	return ok
}

// GetFieldMapStrStructLen 获取 FieldMapStrStruct 的元素数量
func (this *AllTypes) GetFieldMapStrStructLen() int {
	return len(this.FieldMapStrStruct)
}

// GetFieldMapStrStructKeys 返回 FieldMapStrStruct 中所有 key 的切片（顺序不确定）
func (this *AllTypes) GetFieldMapStrStructKeys() []string {
	keys := make([]string, 0, len(this.FieldMapStrStruct))
	for k := range this.FieldMapStrStruct {
		keys = append(keys, k)
	}
	return keys
}

// GetFieldMapStrStructCopy 返回 FieldMapStrStruct 的浅拷贝
func (this *AllTypes) GetFieldMapStrStructCopy() map[string]*BaseInfo {
	return maps.Clone(this.FieldMapStrStruct)
}

// EnsureFieldMapStrStruct 确保 FieldMapStrStruct 已初始化（nil 时自动创建空 map），返回字段引用
func (this *AllTypes) EnsureFieldMapStrStruct() map[string]*BaseInfo {
	if this.FieldMapStrStruct == nil {
		this.FieldMapStrStruct = make(map[string]*BaseInfo)
	}
	return this.FieldMapStrStruct
}

// SetFieldMapStrStructVal 设置 FieldMapStrStruct 中指定 key 的值
func (this *AllTypes) SetFieldMapStrStructVal(key string, value *BaseInfo) {
	this.FieldMapStrStruct[key] = value
}

// DeleteFieldMapStrStructKey 删除 FieldMapStrStruct 中指定 key
func (this *AllTypes) DeleteFieldMapStrStructKey(key string) {
	delete(this.FieldMapStrStruct, key)
}

// 具名 map 类型
// GetFieldMetadataVal 获取 FieldMetadata 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMetadataVal(key string) (string, bool) {
	val, ok := this.FieldMetadata[key]
	return val, ok
}

// GetFieldMetadataValOrDefault 获取 FieldMetadata 中指定 key 的值，key 不存在时返回 def
func (this *AllTypes) GetFieldMetadataValOrDefault(key string, def string) string {
	if val, ok := this.FieldMetadata[key]; ok {
		return val
	}
	return def
}

// RangeFieldMetadata 遍历 FieldMetadata，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMetadata(fn func(key string, value string) bool) {
	for k, v := range this.FieldMetadata {
		if !fn(k, v) {
			break
		}
	}
}

// HasFieldMetadata 返回 FieldMetadata 是否已初始化（非 nil）
func (this *AllTypes) HasFieldMetadata() bool {
	return this.FieldMetadata != nil
}

// HasFieldMetadataKey 检查 FieldMetadata 中指定 key 是否存在
func (this *AllTypes) HasFieldMetadataKey(key string) bool {
	_, ok := this.FieldMetadata[key]
	return ok
}

// GetFieldMetadataLen 获取 FieldMetadata 的元素数量
func (this *AllTypes) GetFieldMetadataLen() int {
	return len(this.FieldMetadata)
}

// GetFieldMetadataKeys 返回 FieldMetadata 中所有 key 的切片（顺序不确定）
func (this *AllTypes) GetFieldMetadataKeys() []string {
	keys := make([]string, 0, len(this.FieldMetadata))
	for k := range this.FieldMetadata {
		keys = append(keys, k)
	}
	return keys
}

// GetFieldMetadataCopy 返回 FieldMetadata 的浅拷贝
func (this *AllTypes) GetFieldMetadataCopy() Metadata {
	return maps.Clone(this.FieldMetadata)
}

// EnsureFieldMetadata 确保 FieldMetadata 已初始化（nil 时自动创建空 map），返回字段引用
func (this *AllTypes) EnsureFieldMetadata() Metadata {
	if this.FieldMetadata == nil {
		this.FieldMetadata = make(Metadata)
	}
	return this.FieldMetadata
}

// SetFieldMetadataVal 设置 FieldMetadata 中指定 key 的值
func (this *AllTypes) SetFieldMetadataVal(key string, value string) {
	this.FieldMetadata[key] = value
}

// DeleteFieldMetadataKey 删除 FieldMetadata 中指定 key
func (this *AllTypes) DeleteFieldMetadataKey(key string) {
	delete(this.FieldMetadata, key)
}

// --- 嵌套复合类型 ---
// GetFieldMapSliceVal 获取 FieldMapSlice 中指定 key 的值，ok 表示 key 是否存在
func (this *AllTypes) GetFieldMapSliceVal(key string) ([]string, bool) {
	val, ok := this.FieldMapSlice[key]
	return val, ok
}

// GetFieldMapSliceValOrDefault 获取 FieldMapSlice 中指定 key 的值，key 不存在时返回 def
func (this *AllTypes) GetFieldMapSliceValOrDefault(key string, def []string) []string {
	if val, ok := this.FieldMapSlice[key]; ok {
		return val
	}
	return def
}

// RangeFieldMapSlice 遍历 FieldMapSlice，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldMapSlice(fn func(key string, value []string) bool) {
	for k, v := range this.FieldMapSlice {
		if !fn(k, v) {
			break
		}
	}
}

// HasFieldMapSlice 返回 FieldMapSlice 是否已初始化（非 nil）
func (this *AllTypes) HasFieldMapSlice() bool {
	return this.FieldMapSlice != nil
}

// HasFieldMapSliceKey 检查 FieldMapSlice 中指定 key 是否存在
func (this *AllTypes) HasFieldMapSliceKey(key string) bool {
	_, ok := this.FieldMapSlice[key]
	return ok
}

// GetFieldMapSliceLen 获取 FieldMapSlice 的元素数量
func (this *AllTypes) GetFieldMapSliceLen() int {
	return len(this.FieldMapSlice)
}

// GetFieldMapSliceKeys 返回 FieldMapSlice 中所有 key 的切片（顺序不确定）
func (this *AllTypes) GetFieldMapSliceKeys() []string {
	keys := make([]string, 0, len(this.FieldMapSlice))
	for k := range this.FieldMapSlice {
		keys = append(keys, k)
	}
	return keys
}

// GetFieldMapSliceCopy 返回 FieldMapSlice 的浅拷贝
func (this *AllTypes) GetFieldMapSliceCopy() map[string][]string {
	return maps.Clone(this.FieldMapSlice)
}

// EnsureFieldMapSlice 确保 FieldMapSlice 已初始化（nil 时自动创建空 map），返回字段引用
func (this *AllTypes) EnsureFieldMapSlice() map[string][]string {
	if this.FieldMapSlice == nil {
		this.FieldMapSlice = make(map[string][]string)
	}
	return this.FieldMapSlice
}

// SetFieldMapSliceVal 设置 FieldMapSlice 中指定 key 的值
func (this *AllTypes) SetFieldMapSliceVal(key string, value []string) {
	this.FieldMapSlice[key] = value
}

// DeleteFieldMapSliceKey 删除 FieldMapSlice 中指定 key
func (this *AllTypes) DeleteFieldMapSliceKey(key string) {
	delete(this.FieldMapSlice, key)
}

// slice elem 是 map
// GetFieldSliceMapAt 获取切片 FieldSliceMap 中 index 位置的元素
func (this *AllTypes) GetFieldSliceMapAt(index int) map[string]int {
	return this.FieldSliceMap[index]
}

// GetFieldSliceMapLen 获取切片 FieldSliceMap 的长度
func (this *AllTypes) GetFieldSliceMapLen() int {
	return len(this.FieldSliceMap)
}

// RangeFieldSliceMap 遍历切片 FieldSliceMap，fn 返回 false 时终止遍历
func (this *AllTypes) RangeFieldSliceMap(fn func(index int, value map[string]int) bool) {
	for i, v := range this.FieldSliceMap {
		if !fn(i, v) {
			break
		}
	}
}

// HasFieldSliceMap 返回切片 FieldSliceMap 是否已初始化（非 nil）
func (this *AllTypes) HasFieldSliceMap() bool {
	return this.FieldSliceMap != nil
}

// GetFieldSliceMapCopy 返回切片 FieldSliceMap 的浅拷贝
func (this *AllTypes) GetFieldSliceMapCopy() []map[string]int {
	return slices.Clone(this.FieldSliceMap)
}

// SetFieldSliceMapAt 设置切片 FieldSliceMap 中 index 位置的元素
func (this *AllTypes) SetFieldSliceMapAt(index int, elem map[string]int) {
	this.FieldSliceMap[index] = elem
}

// AppendFieldSliceMap 向切片 FieldSliceMap 追加一个或多个元素
func (this *AllTypes) AppendFieldSliceMap(elems ...map[string]int) {
	this.FieldSliceMap = append(this.FieldSliceMap, elems...)
}

// DeleteFieldSliceMapAt 删除切片 FieldSliceMap 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AllTypes) DeleteFieldSliceMapAt(index int) {
	this.FieldSliceMap = slices.Delete(this.FieldSliceMap, index, index+1)
}

// 只生成 getter
// GetFieldReadonly 获取 FieldReadonly
func (this *AllTypes) GetFieldReadonly() string {
	return this.FieldReadonly
}

// 只生成 setter
// SetFieldWriteOnly 设置 FieldWriteOnly
func (this *AllTypes) SetFieldWriteOnly(FieldWriteOnly string) {
	this.FieldWriteOnly = FieldWriteOnly
}

// 多个 tag 共存
// GetFieldWithJSON 获取 FieldWithJSON
func (this *AllTypes) GetFieldWithJSON() string {
	return this.FieldWithJSON
}

// --- interface / func 类型：生成 Get/Set ---
// GetFieldInterface 获取 FieldInterface
func (this *AllTypes) GetFieldInterface() interface{} {
	return this.FieldInterface
}

// SetFieldInterface 设置 FieldInterface
func (this *AllTypes) SetFieldInterface(FieldInterface interface{}) {
	this.FieldInterface = FieldInterface
}

// HasFieldInterface 返回 FieldInterface 是否已初始化（非 nil）
func (this *AllTypes) HasFieldInterface() bool {
	return this.FieldInterface != nil
}

// 生成 GetFieldFunc/SetFieldFunc
// GetFieldFunc 获取 FieldFunc
func (this *AllTypes) GetFieldFunc() func(int) string {
	return this.FieldFunc
}

// SetFieldFunc 设置 FieldFunc
func (this *AllTypes) SetFieldFunc(FieldFunc func(int) string) {
	this.FieldFunc = FieldFunc
}

// HasFieldFunc 返回 FieldFunc 是否已初始化（非 nil）
func (this *AllTypes) HasFieldFunc() bool {
	return this.FieldFunc != nil
}

// 生成 GetFieldAny/SetFieldAny（any = interface{}）
// GetFieldAny 获取 FieldAny
func (this *AllTypes) GetFieldAny() any {
	return this.FieldAny
}

// SetFieldAny 设置 FieldAny
func (this *AllTypes) SetFieldAny(FieldAny any) {
	this.FieldAny = FieldAny
}

// HasFieldAny 返回 FieldAny 是否已初始化（非 nil）
func (this *AllTypes) HasFieldAny() bool {
	return this.FieldAny != nil
}
