// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetFixed8 获取数组 Fixed8 的完整副本
func (this *ArrayOnly) GetFixed8() [8]byte {
	return this.Fixed8
}

// GetFixed8At 获取数组 Fixed8 中 index 位置的元素
func (this *ArrayOnly) GetFixed8At(index int) byte {
	return this.Fixed8[index]
}

// GetFixed8Len 获取数组 Fixed8 的长度
func (this *ArrayOnly) GetFixed8Len() int {
	return len(this.Fixed8)
}

// RangeFixed8 遍历数组 Fixed8，fn 返回 false 时终止遍历
func (this *ArrayOnly) RangeFixed8(fn func(index int, value byte) bool) {
	for i, v := range this.Fixed8 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFixed8At 设置数组 Fixed8 中 index 位置的元素
func (this *ArrayOnly) SetFixed8At(index int, elem byte) {
	this.Fixed8[index] = elem
}

// GetFixed16 获取数组 Fixed16 的完整副本
func (this *ArrayOnly) GetFixed16() [16]byte {
	return this.Fixed16
}

// GetFixed16At 获取数组 Fixed16 中 index 位置的元素
func (this *ArrayOnly) GetFixed16At(index int) byte {
	return this.Fixed16[index]
}

// GetFixed16Len 获取数组 Fixed16 的长度
func (this *ArrayOnly) GetFixed16Len() int {
	return len(this.Fixed16)
}

// RangeFixed16 遍历数组 Fixed16，fn 返回 false 时终止遍历
func (this *ArrayOnly) RangeFixed16(fn func(index int, value byte) bool) {
	for i, v := range this.Fixed16 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFixed16At 设置数组 Fixed16 中 index 位置的元素
func (this *ArrayOnly) SetFixed16At(index int, elem byte) {
	this.Fixed16[index] = elem
}

// GetFixed256 获取数组 Fixed256 的完整副本
func (this *ArrayOnly) GetFixed256() [256]int32 {
	return this.Fixed256
}

// GetFixed256At 获取数组 Fixed256 中 index 位置的元素
func (this *ArrayOnly) GetFixed256At(index int) int32 {
	return this.Fixed256[index]
}

// GetFixed256Len 获取数组 Fixed256 的长度
func (this *ArrayOnly) GetFixed256Len() int {
	return len(this.Fixed256)
}

// RangeFixed256 遍历数组 Fixed256，fn 返回 false 时终止遍历
func (this *ArrayOnly) RangeFixed256(fn func(index int, value int32) bool) {
	for i, v := range this.Fixed256 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFixed256At 设置数组 Fixed256 中 index 位置的元素
func (this *ArrayOnly) SetFixed256At(index int, elem int32) {
	this.Fixed256[index] = elem
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *ArrayOnly) Reset() {
	*this = ArrayOnly{}
}
