// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetFixed8Elem 获取数组 Fixed8 中 index 位置的元素
func (this *ArrayOnly) GetFixed8Elem(index int) byte {
	return this.Fixed8[index]
}

// GetFixed8Len 获取数组 Fixed8 的长度
func (this *ArrayOnly) GetFixed8Len() int {
	return len(this.Fixed8)
}

// RangeFixed8 遍历数组 Fixed8，fn 返回 false 时终止遍历
func (this *ArrayOnly) RangeFixed8(fn func(index int, value byte) bool) {
	for i, v := range this.Fixed8 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFixed8Elem 设置数组 Fixed8 中 index 位置的元素
func (this *ArrayOnly) SetFixed8Elem(index int, elem byte) {
	this.Fixed8[index] = elem
}

// GetFixed16Elem 获取数组 Fixed16 中 index 位置的元素
func (this *ArrayOnly) GetFixed16Elem(index int) byte {
	return this.Fixed16[index]
}

// GetFixed16Len 获取数组 Fixed16 的长度
func (this *ArrayOnly) GetFixed16Len() int {
	return len(this.Fixed16)
}

// RangeFixed16 遍历数组 Fixed16，fn 返回 false 时终止遍历
func (this *ArrayOnly) RangeFixed16(fn func(index int, value byte) bool) {
	for i, v := range this.Fixed16 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFixed16Elem 设置数组 Fixed16 中 index 位置的元素
func (this *ArrayOnly) SetFixed16Elem(index int, elem byte) {
	this.Fixed16[index] = elem
}

// GetFixed256Elem 获取数组 Fixed256 中 index 位置的元素
func (this *ArrayOnly) GetFixed256Elem(index int) int32 {
	return this.Fixed256[index]
}

// GetFixed256Len 获取数组 Fixed256 的长度
func (this *ArrayOnly) GetFixed256Len() int {
	return len(this.Fixed256)
}

// RangeFixed256 遍历数组 Fixed256，fn 返回 false 时终止遍历
func (this *ArrayOnly) RangeFixed256(fn func(index int, value int32) bool) {
	for i, v := range this.Fixed256 {
		if !fn(i, v) {
			break
		}
	}
}

// SetFixed256Elem 设置数组 Fixed256 中 index 位置的元素
func (this *ArrayOnly) SetFixed256Elem(index int, elem int32) {
	this.Fixed256[index] = elem
}
