// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import (
	"maps"
	"slices"
)

// GetTagsAt 获取切片 Tags 中 index 位置的元素
func (this *AutoDirtyCollections) GetTagsAt(index int) string {
	return this.Tags[index]
}

// GetTagsLen 获取切片 Tags 的长度
func (this *AutoDirtyCollections) GetTagsLen() int {
	return len(this.Tags)
}

// RangeTags 遍历切片 Tags，fn 返回 false 时终止遍历
func (this *AutoDirtyCollections) RangeTags(fn func(index int, value string) bool) {
	for i, v := range this.Tags {
		if !fn(i, v) {
			break
		}
	}
}

// HasTags 返回切片 Tags 是否已初始化（非 nil）
func (this *AutoDirtyCollections) HasTags() bool {
	return this.Tags != nil
}

// GetTagsCopy 返回切片 Tags 的浅拷贝
func (this *AutoDirtyCollections) GetTagsCopy() []string {
	return slices.Clone(this.Tags)
}

// SetTagsAt 设置切片 Tags 中 index 位置的元素
func (this *AutoDirtyCollections) SetTagsAt(index int, elem string) {
	this.Tags[index] = elem
	this.MakeDirty() // 需业务层实现此方法
}

// AppendTags 向切片 Tags 追加一个或多个元素
func (this *AutoDirtyCollections) AppendTags(elems ...string) {
	this.Tags = append(this.Tags, elems...)
	this.MakeDirty() // 需业务层实现此方法
}

// DeleteTagsAt 删除切片 Tags 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AutoDirtyCollections) DeleteTagsAt(index int) {
	this.Tags = slices.Delete(this.Tags, index, index+1)
	this.MakeDirty() // 需业务层实现此方法
}

// GetAttrsVal 获取 Attrs 中指定 key 的值，ok 表示 key 是否存在
func (this *AutoDirtyCollections) GetAttrsVal(key string) (int32, bool) {
	val, ok := this.Attrs[key]
	return val, ok
}

// GetAttrsValOrDefault 获取 Attrs 中指定 key 的值，key 不存在时返回 def
func (this *AutoDirtyCollections) GetAttrsValOrDefault(key string, def int32) int32 {
	if val, ok := this.Attrs[key]; ok {
		return val
	}
	return def
}

// RangeAttrs 遍历 Attrs，fn 返回 false 时终止遍历
func (this *AutoDirtyCollections) RangeAttrs(fn func(key string, value int32) bool) {
	for k, v := range this.Attrs {
		if !fn(k, v) {
			break
		}
	}
}

// HasAttrs 返回 Attrs 是否已初始化（非 nil）
func (this *AutoDirtyCollections) HasAttrs() bool {
	return this.Attrs != nil
}

// HasAttrsKey 检查 Attrs 中指定 key 是否存在
func (this *AutoDirtyCollections) HasAttrsKey(key string) bool {
	_, ok := this.Attrs[key]
	return ok
}

// GetAttrsLen 获取 Attrs 的元素数量
func (this *AutoDirtyCollections) GetAttrsLen() int {
	return len(this.Attrs)
}

// GetAttrsKeys 返回 Attrs 中所有 key 的切片（顺序不确定）
func (this *AutoDirtyCollections) GetAttrsKeys() []string {
	keys := make([]string, 0, len(this.Attrs))
	for k := range this.Attrs {
		keys = append(keys, k)
	}
	return keys
}

// GetAttrsCopy 返回 Attrs 的浅拷贝
func (this *AutoDirtyCollections) GetAttrsCopy() map[string]int32 {
	return maps.Clone(this.Attrs)
}

// EnsureAttrs 确保 Attrs 已初始化（nil 时自动创建空 map），返回字段引用
func (this *AutoDirtyCollections) EnsureAttrs() map[string]int32 {
	if this.Attrs == nil {
		this.Attrs = make(map[string]int32)
	}
	return this.Attrs
}

// SetAttrsVal 设置 Attrs 中指定 key 的值
func (this *AutoDirtyCollections) SetAttrsVal(key string, value int32) {
	this.Attrs[key] = value
	this.MakeDirty() // 需业务层实现此方法
}

// DeleteAttrsKey 删除 Attrs 中指定 key
func (this *AutoDirtyCollections) DeleteAttrsKey(key string) {
	delete(this.Attrs, key)
	this.MakeDirty() // 需业务层实现此方法
}

// 数组 SetAt，元素 int32 可比较，有幂等检查
// GetNums 获取数组 Nums 的完整副本
func (this *AutoDirtyCollections) GetNums() [4]int32 {
	return this.Nums
}

// GetNumsAt 获取数组 Nums 中 index 位置的元素
func (this *AutoDirtyCollections) GetNumsAt(index int) int32 {
	return this.Nums[index]
}

// GetNumsLen 获取数组 Nums 的长度
func (this *AutoDirtyCollections) GetNumsLen() int {
	return len(this.Nums)
}

// RangeNums 遍历数组 Nums，fn 返回 false 时终止遍历
func (this *AutoDirtyCollections) RangeNums(fn func(index int, value int32) bool) {
	for i, v := range this.Nums {
		if !fn(i, v) {
			break
		}
	}
}

// SetNumsAt 设置数组 Nums 中 index 位置的元素
func (this *AutoDirtyCollections) SetNumsAt(index int, elem int32) {
	this.Nums[index] = elem
	this.MakeDirty() // 需业务层实现此方法
}
