// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import (
	"maps"
	"slices"
)

// GetGold 获取 Gold
func (this *AutoDirtyPlayer) GetGold() int64 {
	return this.Gold
}

// SetGold 设置 Gold
func (this *AutoDirtyPlayer) SetGold(Gold int64) {
	if this.Gold == Gold {
		return
	}
	this.Gold = Gold
	this.MakeDirty() // 需业务层实现此方法
}

// AddGold 将 Gold 增加 delta
func (this *AutoDirtyPlayer) AddGold(delta int64) {
	this.Gold += delta
	this.MakeDirty() // 需业务层实现此方法
}

// SubGold 将 Gold 减少 delta
func (this *AutoDirtyPlayer) SubGold(delta int64) {
	this.Gold -= delta
	this.MakeDirty() // 需业务层实现此方法
}

// GetScore 获取 Score
func (this *AutoDirtyPlayer) GetScore() float64 {
	return this.Score
}

// SetScore 设置 Score
func (this *AutoDirtyPlayer) SetScore(Score float64) {
	if this.Score == Score {
		return
	}
	this.Score = Score
	this.MakeDirty() // 需业务层实现此方法
}

// AddScore 将 Score 增加 delta
func (this *AutoDirtyPlayer) AddScore(delta float64) {
	this.Score += delta
	this.MakeDirty() // 需业务层实现此方法
}

// SubScore 将 Score 减少 delta
func (this *AutoDirtyPlayer) SubScore(delta float64) {
	this.Score -= delta
	this.MakeDirty() // 需业务层实现此方法
}

// GetTagsAt 获取切片 Tags 中 index 位置的元素
func (this *AutoDirtyPlayer) GetTagsAt(index int) string {
	return this.Tags[index]
}

// GetTagsLen 获取切片 Tags 的长度
func (this *AutoDirtyPlayer) GetTagsLen() int {
	return len(this.Tags)
}

// RangeTags 遍历切片 Tags，fn 返回 false 时终止遍历
func (this *AutoDirtyPlayer) RangeTags(fn func(index int, value string) bool) {
	for i, v := range this.Tags {
		if !fn(i, v) {
			break
		}
	}
}

// HasTags 返回切片 Tags 是否已初始化（非 nil）
func (this *AutoDirtyPlayer) HasTags() bool {
	return this.Tags != nil
}

// GetTagsCopy 返回切片 Tags 的浅拷贝
func (this *AutoDirtyPlayer) GetTagsCopy() []string {
	return slices.Clone(this.Tags)
}

// SetTagsAt 设置切片 Tags 中 index 位置的元素
func (this *AutoDirtyPlayer) SetTagsAt(index int, elem string) {
	if this.Tags[index] == elem {
		return
	}
	this.Tags[index] = elem
	this.MakeDirty() // 需业务层实现此方法
}

// AppendTags 向切片 Tags 追加一个或多个元素
func (this *AutoDirtyPlayer) AppendTags(elems ...string) {
	this.Tags = append(this.Tags, elems...)
	this.MakeDirty() // 需业务层实现此方法
}

// DeleteTagsAt 删除切片 Tags 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *AutoDirtyPlayer) DeleteTagsAt(index int) {
	this.Tags = slices.Delete(this.Tags, index, index+1)
	this.MakeDirty() // 需业务层实现此方法
}

// GetAttrsVal 获取 Attrs 中指定 key 的值，ok 表示 key 是否存在
func (this *AutoDirtyPlayer) GetAttrsVal(key string) (string, bool) {
	val, ok := this.Attrs[key]
	return val, ok
}

// GetAttrsValOrDefault 获取 Attrs 中指定 key 的值，key 不存在时返回 def
func (this *AutoDirtyPlayer) GetAttrsValOrDefault(key string, def string) string {
	if val, ok := this.Attrs[key]; ok {
		return val
	}
	return def
}

// RangeAttrs 遍历 Attrs，fn 返回 false 时终止遍历
func (this *AutoDirtyPlayer) RangeAttrs(fn func(key string, value string) bool) {
	for k, v := range this.Attrs {
		if !fn(k, v) {
			break
		}
	}
}

// HasAttrs 返回 Attrs 是否已初始化（非 nil）
func (this *AutoDirtyPlayer) HasAttrs() bool {
	return this.Attrs != nil
}

// HasAttrsKey 检查 Attrs 中指定 key 是否存在
func (this *AutoDirtyPlayer) HasAttrsKey(key string) bool {
	_, ok := this.Attrs[key]
	return ok
}

// GetAttrsLen 获取 Attrs 的元素数量
func (this *AutoDirtyPlayer) GetAttrsLen() int {
	return len(this.Attrs)
}

// GetAttrsKeys 返回 Attrs 中所有 key 的切片（顺序不确定）
func (this *AutoDirtyPlayer) GetAttrsKeys() []string {
	keys := make([]string, 0, len(this.Attrs))
	for k := range this.Attrs {
		keys = append(keys, k)
	}
	return keys
}

// GetAttrsCopy 返回 Attrs 的浅拷贝
func (this *AutoDirtyPlayer) GetAttrsCopy() map[string]string {
	return maps.Clone(this.Attrs)
}

// EnsureAttrs 确保 Attrs 已初始化（nil 时自动创建空 map），返回字段引用
func (this *AutoDirtyPlayer) EnsureAttrs() map[string]string {
	if this.Attrs == nil {
		this.Attrs = make(map[string]string)
	}
	return this.Attrs
}

// SetAttrsVal 设置 Attrs 中指定 key 的值
func (this *AutoDirtyPlayer) SetAttrsVal(key string, value string) {
	this.Attrs[key] = value
	this.MakeDirty() // 需业务层实现此方法
}

// DeleteAttrsKey 删除 Attrs 中指定 key
func (this *AutoDirtyPlayer) DeleteAttrsKey(key string) {
	delete(this.Attrs, key)
	this.MakeDirty() // 需业务层实现此方法
}
