// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import "time"

// GetCreatedAt 获取 CreatedAt
func (this *BaseInfo) GetCreatedAt() time.Time {
	return this.CreatedAt
}

// SetCreatedAt 设置 CreatedAt
func (this *BaseInfo) SetCreatedAt(CreatedAt time.Time) {
	this.CreatedAt = CreatedAt
}

// GetUpdatedAt 获取 UpdatedAt
func (this *BaseInfo) GetUpdatedAt() time.Time {
	return this.UpdatedAt
}

// SetUpdatedAt 设置 UpdatedAt
func (this *BaseInfo) SetUpdatedAt(UpdatedAt time.Time) {
	this.UpdatedAt = UpdatedAt
}
