// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// Item 存储的元素
// GetItem 获取 Item
func (this *Container[T]) GetItem() T {
	return this.Item
}

// SetItem 设置 Item
func (this *Container[T]) SetItem(Item T) {
	this.Item = Item
}

// Size 当前大小
// GetSize 获取 Size
func (this *Container[T]) GetSize() int {
	return this.Size
}

// SetSize 设置 Size
func (this *Container[T]) SetSize(Size int) {
	this.Size = Size
}

// AddSize 将 Size 增加 delta
func (this *Container[T]) AddSize(delta int) {
	this.Size += delta
}

// SubSize 将 Size 减少 delta
func (this *Container[T]) SubSize(delta int) {
	this.Size -= delta
}
