// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// 命名字段，应生成 GetBase/SetBase
// GetBase 获取 Base
func (this *EmbedOther) GetBase() BaseInfo {
	return this.Base
}

// SetBase 设置 Base
func (this *EmbedOther) SetBase(Base BaseInfo) {
	this.Base = Base
}

// 指针，应生成 GetBasePtr/SetBasePtr
// GetBasePtr 获取 BasePtr
func (this *EmbedOther) GetBasePtr() *BaseInfo {
	return this.BasePtr
}

// SetBasePtr 设置 BasePtr
func (this *EmbedOther) SetBasePtr(BasePtr *BaseInfo) {
	this.BasePtr = BasePtr
}
