// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetID 获取 ID
func (this *EmbedDeep) GetID() int {
	return this.ID
}

// SetID 设置 ID
func (this *EmbedDeep) SetID(ID int) {
	this.ID = ID
}

// AddID 将 ID 增加 delta
func (this *EmbedDeep) AddID(delta int) {
	this.ID += delta
}

// SubID 将 ID 减少 delta
func (this *EmbedDeep) SubID(delta int) {
	this.ID -= delta
}
