// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetGold 获取 Gold
func (this *FieldOverrideEntity) GetGold() int64 {
	return this.Gold
}

// SetGold 设置 Gold
func (this *FieldOverrideEntity) SetGold(Gold int64) {
	this.Gold = Gold
	this.MakeDirty() // 需业务层实现此方法
}

// AddGold 将 Gold 增加 delta
func (this *FieldOverrideEntity) AddGold(delta int64) {
	this.Gold += delta
	this.MakeDirty() // 需业务层实现此方法
}

// SubGold 将 Gold 减少 delta
func (this *FieldOverrideEntity) SubGold(delta int64) {
	this.Gold -= delta
	this.MakeDirty() // 需业务层实现此方法
}

// 覆盖结构体级
// GetModuleScore 获取 ModuleScore
func (this *FieldOverrideEntity) GetModuleScore() int64 {
	return this.ModuleScore
}

// SetModuleScore 设置 ModuleScore
func (this *FieldOverrideEntity) SetModuleScore(ModuleScore int64) {
	this.ModuleScore = ModuleScore
	this.MarkModule() // 需业务层实现此方法
}

// AddModuleScore 将 ModuleScore 增加 delta
func (this *FieldOverrideEntity) AddModuleScore(delta int64) {
	this.ModuleScore += delta
	this.MarkModule() // 需业务层实现此方法
}

// SubModuleScore 将 ModuleScore 减少 delta
func (this *FieldOverrideEntity) SubModuleScore(delta int64) {
	this.ModuleScore -= delta
	this.MarkModule() // 需业务层实现此方法
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *FieldOverrideEntity) Reset() {
	*this = FieldOverrideEntity{}
	this.MakeDirty() // 需业务层实现此方法
}
