// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetGold 获取 Gold
func (this *FieldOverrideEntity) GetGold() int64 {
	return this.Gold
}

// SetGold 设置 Gold
func (this *FieldOverrideEntity) SetGold(Gold int64) {
	this.Gold = Gold
}

// AddGold 将 Gold 增加 delta
func (this *FieldOverrideEntity) AddGold(delta int64) {
	this.Gold += delta
}

// SubGold 将 Gold 减少 delta
func (this *FieldOverrideEntity) SubGold(delta int64) {
	this.Gold -= delta
}

// GetModuleScore 获取 ModuleScore
func (this *FieldOverrideEntity) GetModuleScore() int64 {
	return this.ModuleScore
}

// SetModuleScore 设置 ModuleScore
func (this *FieldOverrideEntity) SetModuleScore(ModuleScore int64) {
	this.ModuleScore = ModuleScore
}

// AddModuleScore 将 ModuleScore 增加 delta
func (this *FieldOverrideEntity) AddModuleScore(delta int64) {
	this.ModuleScore += delta
}

// SubModuleScore 将 ModuleScore 减少 delta
func (this *FieldOverrideEntity) SubModuleScore(delta int64) {
	this.ModuleScore -= delta
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *FieldOverrideEntity) Reset() {
	*this = FieldOverrideEntity{}
	this.MakeDirty()
}

// Apply 在 fn 中修改结构体内容，fn 执行完毕后自动调用 MakeDirty()；fn panic 时不调用。
// 适用于所有类型的字段变更，包括嵌入的自定义结构体和第三方类型。
//
// 示例（obj 为该结构体的变量）：
//
//	obj.Apply(func() {
//	    obj.SetXxx(newValue)
//	})
//
// 注意：
//   - fn 是无参闭包，编译器不验证闭包内操作的目标；作用域内有多个对象时，
//     确保闭包引用的是调用 Apply 的那个变量，而非其他同类对象。
//   - 嵌套调用 Apply 会触发多次 MakeDirty()，仅在后者幂等时无害。
func (this *FieldOverrideEntity) Apply(fn func()) {
	fn()
	this.MakeDirty()
}
