// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetIndexVal 获取 Index 中指定 key 的值，ok 表示 key 是否存在
func (this *MapOnly) GetIndexVal(key int) (string, bool) {
	val, ok := this.Index[key]
	return val, ok
}

// RangeIndex 遍历 Index，fn 返回 false 时终止遍历
func (this *MapOnly) RangeIndex(fn func(key int, value string) bool) {
	for k, v := range this.Index {
		if !fn(k, v) {
			break
		}
	}
}

// SetIndexKV 设置 Index 中指定 key 的值
func (this *MapOnly) SetIndexKV(key int, value string) {
	this.Index[key] = value
}

// DelIndexKV 删除 Index 中指定 key
func (this *MapOnly) DelIndexKV(key int) {
	delete(this.Index, key)
}

// value 是 interface，生成 key/value 类型要正确
// GetConfigVal 获取 Config 中指定 key 的值，ok 表示 key 是否存在
func (this *MapOnly) GetConfigVal(key string) (interface{}, bool) {
	val, ok := this.Config[key]
	return val, ok
}

// RangeConfig 遍历 Config，fn 返回 false 时终止遍历
func (this *MapOnly) RangeConfig(fn func(key string, value interface{}) bool) {
	for k, v := range this.Config {
		if !fn(k, v) {
			break
		}
	}
}

// SetConfigKV 设置 Config 中指定 key 的值
func (this *MapOnly) SetConfigKV(key string, value interface{}) {
	this.Config[key] = value
}

// DelConfigKV 删除 Config 中指定 key
func (this *MapOnly) DelConfigKV(key string) {
	delete(this.Config, key)
}

// value 是 slice
// GetNestedVal 获取 Nested 中指定 key 的值，ok 表示 key 是否存在
func (this *MapOnly) GetNestedVal(key string) ([]int, bool) {
	val, ok := this.Nested[key]
	return val, ok
}

// RangeNested 遍历 Nested，fn 返回 false 时终止遍历
func (this *MapOnly) RangeNested(fn func(key string, value []int) bool) {
	for k, v := range this.Nested {
		if !fn(k, v) {
			break
		}
	}
}

// SetNestedKV 设置 Nested 中指定 key 的值
func (this *MapOnly) SetNestedKV(key string, value []int) {
	this.Nested[key] = value
}

// DelNestedKV 删除 Nested 中指定 key
func (this *MapOnly) DelNestedKV(key string) {
	delete(this.Nested, key)
}
