// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// nodirty 最高优先级，此 tag 无效
// GetGold 获取 Gold
func (this *NoDirtyPlayer) GetGold() int64 {
	return this.Gold
}

// SetGold 设置 Gold
func (this *NoDirtyPlayer) SetGold(Gold int64) {
	this.Gold = Gold
}

// AddGold 将 Gold 增加 delta
func (this *NoDirtyPlayer) AddGold(delta int64) {
	this.Gold += delta
}

// SubGold 将 Gold 减少 delta
func (this *NoDirtyPlayer) SubGold(delta int64) {
	this.Gold -= delta
}

// GetScore 获取 Score
func (this *NoDirtyPlayer) GetScore() float64 {
	return this.Score
}

// SetScore 设置 Score
func (this *NoDirtyPlayer) SetScore(Score float64) {
	this.Score = Score
}

// AddScore 将 Score 增加 delta
func (this *NoDirtyPlayer) AddScore(delta float64) {
	this.Score += delta
}

// SubScore 将 Score 减少 delta
func (this *NoDirtyPlayer) SubScore(delta float64) {
	this.Score -= delta
}
