// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetCount 获取 Count
func (this *OverrideEmbed) GetCount() int {
	return this.Count
}

// SetCount 设置 Count
func (this *OverrideEmbed) SetCount(Count int) {
	this.Count = Count
}

// AddCount 将 Count 增加 delta
func (this *OverrideEmbed) AddCount(delta int) {
	this.Count += delta
}

// SubCount 将 Count 减少 delta
func (this *OverrideEmbed) SubCount(delta int) {
	this.Count -= delta
}

// GetName 获取 Name
func (this *OverrideEmbed) GetName() string {
	return this.Name
}

// SetName 设置 Name
func (this *OverrideEmbed) SetName(Name string) {
	this.Name = Name
}
