// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// Key 键
// GetKey 获取 Key
func (this *Pair[K, V]) GetKey() K {
	return this.Key
}

// SetKey 设置 Key
func (this *Pair[K, V]) SetKey(Key K) {
	this.Key = Key
}

// Value 值
// GetValue 获取 Value
func (this *Pair[K, V]) GetValue() V {
	return this.Value
}

// SetValue 设置 Value
func (this *Pair[K, V]) SetValue(Value V) {
	this.Value = Value
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *Pair[K, V]) Reset() {
	*this = Pair[K, V]{}
}
