// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetID 获取 ID
func (this *PlainStruct) GetID() int64 {
	return this.ID
}

// SetID 设置 ID
func (this *PlainStruct) SetID(ID int64) {
	this.ID = ID
}

// GetScore 获取 Score
func (this *PlainStruct) GetScore() float64 {
	return this.Score
}

// SetScore 设置 Score
func (this *PlainStruct) SetScore(Score float64) {
	this.Score = Score
}

// GetName 获取 Name
func (this *PlainStruct) GetName() string {
	return this.Name
}

// SetName 设置 Name
func (this *PlainStruct) SetName(Name string) {
	this.Name = Name
}

// GetFlag 获取 Flag
func (this *PlainStruct) GetFlag() bool {
	return this.Flag
}

// SetFlag 设置 Flag
func (this *PlainStruct) SetFlag(Flag bool) {
	this.Flag = Flag
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *PlainStruct) Reset() {
	*this = PlainStruct{}
}
