// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetName 获取 Name
func (this *ResetWithDirtyPlayer) GetName() string {
	return this.Name
}

// SetName 设置 Name
func (this *ResetWithDirtyPlayer) SetName(Name string) {
	if this.Name == Name {
		return
	}
	this.Name = Name
	this.MakeDirty() // 需业务层实现此方法
}

// GetLevel 获取 Level
func (this *ResetWithDirtyPlayer) GetLevel() int32 {
	return this.Level
}

// SetLevel 设置 Level
func (this *ResetWithDirtyPlayer) SetLevel(Level int32) {
	if this.Level == Level {
		return
	}
	this.Level = Level
	this.MakeDirty() // 需业务层实现此方法
}

// AddLevel 将 Level 增加 delta
func (this *ResetWithDirtyPlayer) AddLevel(delta int32) {
	this.Level += delta
	this.MakeDirty() // 需业务层实现此方法
}

// SubLevel 将 Level 减少 delta
func (this *ResetWithDirtyPlayer) SubLevel(delta int32) {
	this.Level -= delta
	this.MakeDirty() // 需业务层实现此方法
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *ResetWithDirtyPlayer) Reset() {
	*this = ResetWithDirtyPlayer{}
	this.MakeDirty() // 需业务层实现此方法
}
