// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetName 获取 Name
func (this *ResetWithDirtyPlayer) GetName() string {
	return this.Name
}

// SetName 设置 Name
func (this *ResetWithDirtyPlayer) SetName(Name string) {
	this.Name = Name
}

// GetLevel 获取 Level
func (this *ResetWithDirtyPlayer) GetLevel() int32 {
	return this.Level
}

// SetLevel 设置 Level
func (this *ResetWithDirtyPlayer) SetLevel(Level int32) {
	this.Level = Level
}

// AddLevel 将 Level 增加 delta
func (this *ResetWithDirtyPlayer) AddLevel(delta int32) {
	this.Level += delta
}

// SubLevel 将 Level 减少 delta
func (this *ResetWithDirtyPlayer) SubLevel(delta int32) {
	this.Level -= delta
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *ResetWithDirtyPlayer) Reset() {
	*this = ResetWithDirtyPlayer{}
	this.MakeDirty()
}

// Modify 在 fn 中修改结构体内容，fn 执行完毕后自动调用 MakeDirty()，若 fn 发生 panic 则不调用。
// 适用于所有类型的字段变更，包括嵌入的自定义结构体和第三方类型。
func (this *ResetWithDirtyPlayer) Modify(fn func(*ResetWithDirtyPlayer)) {
	fn(this)
	this.MakeDirty()
}
