// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import "slices"

// GetNamesAt 获取切片 Names 中 index 位置的元素
func (this *SliceOnly) GetNamesAt(index int) string {
	return this.Names[index]
}

// GetNamesLen 获取切片 Names 的长度
func (this *SliceOnly) GetNamesLen() int {
	return len(this.Names)
}

// RangeNames 遍历切片 Names，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeNames(fn func(index int, value string) bool) {
	for i, v := range this.Names {
		if !fn(i, v) {
			break
		}
	}
}

// HasNames 返回切片 Names 是否已初始化（非 nil）
func (this *SliceOnly) HasNames() bool {
	return this.Names != nil
}

// GetNamesCopy 返回切片 Names 的浅拷贝
func (this *SliceOnly) GetNamesCopy() []string {
	return slices.Clone(this.Names)
}

// EnsureNames 确保切片 Names 已初始化（nil 时自动创建空切片），返回字段引用
func (this *SliceOnly) EnsureNames() []string {
	if this.Names == nil {
		this.Names = make([]string, 0)
	}
	return this.Names
}

// SetNamesAt 设置切片 Names 中 index 位置的元素
func (this *SliceOnly) SetNamesAt(index int, elem string) {
	this.Names[index] = elem
}

// AppendNames 向切片 Names 追加元素
func (this *SliceOnly) AppendNames(elem string) {
	this.Names = append(this.Names, elem)
}

// RemoveNames 删除切片 Names 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) RemoveNames(index int) {
	this.Names = append(this.Names[:index], this.Names[index+1:]...)
}

// GetScoresAt 获取切片 Scores 中 index 位置的元素
func (this *SliceOnly) GetScoresAt(index int) float64 {
	return this.Scores[index]
}

// GetScoresLen 获取切片 Scores 的长度
func (this *SliceOnly) GetScoresLen() int {
	return len(this.Scores)
}

// RangeScores 遍历切片 Scores，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeScores(fn func(index int, value float64) bool) {
	for i, v := range this.Scores {
		if !fn(i, v) {
			break
		}
	}
}

// HasScores 返回切片 Scores 是否已初始化（非 nil）
func (this *SliceOnly) HasScores() bool {
	return this.Scores != nil
}

// GetScoresCopy 返回切片 Scores 的浅拷贝
func (this *SliceOnly) GetScoresCopy() []float64 {
	return slices.Clone(this.Scores)
}

// EnsureScores 确保切片 Scores 已初始化（nil 时自动创建空切片），返回字段引用
func (this *SliceOnly) EnsureScores() []float64 {
	if this.Scores == nil {
		this.Scores = make([]float64, 0)
	}
	return this.Scores
}

// SetScoresAt 设置切片 Scores 中 index 位置的元素
func (this *SliceOnly) SetScoresAt(index int, elem float64) {
	this.Scores[index] = elem
}

// AppendScores 向切片 Scores 追加元素
func (this *SliceOnly) AppendScores(elem float64) {
	this.Scores = append(this.Scores, elem)
}

// RemoveScores 删除切片 Scores 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) RemoveScores(index int) {
	this.Scores = append(this.Scores[:index], this.Scores[index+1:]...)
}

// GetItemsAt 获取切片 Items 中 index 位置的元素
func (this *SliceOnly) GetItemsAt(index int) *BaseInfo {
	return this.Items[index]
}

// GetItemsLen 获取切片 Items 的长度
func (this *SliceOnly) GetItemsLen() int {
	return len(this.Items)
}

// RangeItems 遍历切片 Items，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeItems(fn func(index int, value *BaseInfo) bool) {
	for i, v := range this.Items {
		if !fn(i, v) {
			break
		}
	}
}

// HasItems 返回切片 Items 是否已初始化（非 nil）
func (this *SliceOnly) HasItems() bool {
	return this.Items != nil
}

// GetItemsCopy 返回切片 Items 的浅拷贝
func (this *SliceOnly) GetItemsCopy() []*BaseInfo {
	return slices.Clone(this.Items)
}

// EnsureItems 确保切片 Items 已初始化（nil 时自动创建空切片），返回字段引用
func (this *SliceOnly) EnsureItems() []*BaseInfo {
	if this.Items == nil {
		this.Items = make([]*BaseInfo, 0)
	}
	return this.Items
}

// SetItemsAt 设置切片 Items 中 index 位置的元素
func (this *SliceOnly) SetItemsAt(index int, elem *BaseInfo) {
	this.Items[index] = elem
}

// AppendItems 向切片 Items 追加元素
func (this *SliceOnly) AppendItems(elem *BaseInfo) {
	this.Items = append(this.Items, elem)
}

// RemoveItems 删除切片 Items 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) RemoveItems(index int) {
	this.Items = append(this.Items[:index], this.Items[index+1:]...)
}
