// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// GetNamesElem 获取切片 Names 中 index 位置的元素
func (this *SliceOnly) GetNamesElem(index int) string {
	return this.Names[index]
}

// GetNamesLen 获取切片 Names 的长度
func (this *SliceOnly) GetNamesLen() int {
	return len(this.Names)
}

// GetNamesCap 获取切片 Names 的容量
func (this *SliceOnly) GetNamesCap() int {
	return cap(this.Names)
}

// RangeNames 遍历切片 Names，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeNames(fn func(index int, value string) bool) {
	for i, v := range this.Names {
		if !fn(i, v) {
			break
		}
	}
}

// SetNamesElem 设置切片 Names 中 index 位置的元素
func (this *SliceOnly) SetNamesElem(index int, elem string) {
	this.Names[index] = elem
}

// AddNamesElem 向切片 Names 追加元素
func (this *SliceOnly) AddNamesElem(elem string) {
	this.Names = append(this.Names, elem)
}

// DelNamesElem 删除切片 Names 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) DelNamesElem(index int) {
	this.Names = append(this.Names[:index], this.Names[index+1:]...)
}

// GetScoresElem 获取切片 Scores 中 index 位置的元素
func (this *SliceOnly) GetScoresElem(index int) float64 {
	return this.Scores[index]
}

// GetScoresLen 获取切片 Scores 的长度
func (this *SliceOnly) GetScoresLen() int {
	return len(this.Scores)
}

// GetScoresCap 获取切片 Scores 的容量
func (this *SliceOnly) GetScoresCap() int {
	return cap(this.Scores)
}

// RangeScores 遍历切片 Scores，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeScores(fn func(index int, value float64) bool) {
	for i, v := range this.Scores {
		if !fn(i, v) {
			break
		}
	}
}

// SetScoresElem 设置切片 Scores 中 index 位置的元素
func (this *SliceOnly) SetScoresElem(index int, elem float64) {
	this.Scores[index] = elem
}

// AddScoresElem 向切片 Scores 追加元素
func (this *SliceOnly) AddScoresElem(elem float64) {
	this.Scores = append(this.Scores, elem)
}

// DelScoresElem 删除切片 Scores 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) DelScoresElem(index int) {
	this.Scores = append(this.Scores[:index], this.Scores[index+1:]...)
}

// GetItemsElem 获取切片 Items 中 index 位置的元素
func (this *SliceOnly) GetItemsElem(index int) *BaseInfo {
	return this.Items[index]
}

// GetItemsLen 获取切片 Items 的长度
func (this *SliceOnly) GetItemsLen() int {
	return len(this.Items)
}

// GetItemsCap 获取切片 Items 的容量
func (this *SliceOnly) GetItemsCap() int {
	return cap(this.Items)
}

// RangeItems 遍历切片 Items，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeItems(fn func(index int, value *BaseInfo) bool) {
	for i, v := range this.Items {
		if !fn(i, v) {
			break
		}
	}
}

// SetItemsElem 设置切片 Items 中 index 位置的元素
func (this *SliceOnly) SetItemsElem(index int, elem *BaseInfo) {
	this.Items[index] = elem
}

// AddItemsElem 向切片 Items 追加元素
func (this *SliceOnly) AddItemsElem(elem *BaseInfo) {
	this.Items = append(this.Items, elem)
}

// DelItemsElem 删除切片 Items 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) DelItemsElem(index int) {
	this.Items = append(this.Items[:index], this.Items[index+1:]...)
}
