// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import "slices"

// GetNamesAt 获取切片 Names 中 index 位置的元素
func (this *SliceOnly) GetNamesAt(index int) string {
	return this.Names[index]
}

// GetNamesLen 获取切片 Names 的长度
func (this *SliceOnly) GetNamesLen() int {
	return len(this.Names)
}

// RangeNames 遍历切片 Names，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeNames(fn func(index int, value string) bool) {
	for i, v := range this.Names {
		if !fn(i, v) {
			break
		}
	}
}

// HasNames 返回切片 Names 是否已初始化（非 nil）
func (this *SliceOnly) HasNames() bool {
	return this.Names != nil
}

// GetNamesCopy 返回切片 Names 的浅拷贝
func (this *SliceOnly) GetNamesCopy() []string {
	return slices.Clone(this.Names)
}

// SetNamesAt 设置切片 Names 中 index 位置的元素
func (this *SliceOnly) SetNamesAt(index int, elem string) {
	this.Names[index] = elem
}

// AppendNames 向切片 Names 追加一个或多个元素
func (this *SliceOnly) AppendNames(elems ...string) {
	this.Names = append(this.Names, elems...)
}

// DeleteNamesAt 删除切片 Names 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) DeleteNamesAt(index int) {
	this.Names = slices.Delete(this.Names, index, index+1)
}

// GetScoresAt 获取切片 Scores 中 index 位置的元素
func (this *SliceOnly) GetScoresAt(index int) float64 {
	return this.Scores[index]
}

// GetScoresLen 获取切片 Scores 的长度
func (this *SliceOnly) GetScoresLen() int {
	return len(this.Scores)
}

// RangeScores 遍历切片 Scores，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeScores(fn func(index int, value float64) bool) {
	for i, v := range this.Scores {
		if !fn(i, v) {
			break
		}
	}
}

// HasScores 返回切片 Scores 是否已初始化（非 nil）
func (this *SliceOnly) HasScores() bool {
	return this.Scores != nil
}

// GetScoresCopy 返回切片 Scores 的浅拷贝
func (this *SliceOnly) GetScoresCopy() []float64 {
	return slices.Clone(this.Scores)
}

// SetScoresAt 设置切片 Scores 中 index 位置的元素
func (this *SliceOnly) SetScoresAt(index int, elem float64) {
	this.Scores[index] = elem
}

// AppendScores 向切片 Scores 追加一个或多个元素
func (this *SliceOnly) AppendScores(elems ...float64) {
	this.Scores = append(this.Scores, elems...)
}

// DeleteScoresAt 删除切片 Scores 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) DeleteScoresAt(index int) {
	this.Scores = slices.Delete(this.Scores, index, index+1)
}

// GetItemsAt 获取切片 Items 中 index 位置的元素
func (this *SliceOnly) GetItemsAt(index int) *BaseInfo {
	return this.Items[index]
}

// GetItemsLen 获取切片 Items 的长度
func (this *SliceOnly) GetItemsLen() int {
	return len(this.Items)
}

// RangeItems 遍历切片 Items，fn 返回 false 时终止遍历
func (this *SliceOnly) RangeItems(fn func(index int, value *BaseInfo) bool) {
	for i, v := range this.Items {
		if !fn(i, v) {
			break
		}
	}
}

// HasItems 返回切片 Items 是否已初始化（非 nil）
func (this *SliceOnly) HasItems() bool {
	return this.Items != nil
}

// GetItemsCopy 返回切片 Items 的浅拷贝
func (this *SliceOnly) GetItemsCopy() []*BaseInfo {
	return slices.Clone(this.Items)
}

// SetItemsAt 设置切片 Items 中 index 位置的元素
func (this *SliceOnly) SetItemsAt(index int, elem *BaseInfo) {
	this.Items[index] = elem
}

// AppendItems 向切片 Items 追加一个或多个元素
func (this *SliceOnly) AppendItems(elems ...*BaseInfo) {
	this.Items = append(this.Items, elems...)
}

// DeleteItemsAt 删除切片 Items 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *SliceOnly) DeleteItemsAt(index int) {
	this.Items = slices.Delete(this.Items, index, index+1)
}
