// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

import "slices"

// 无 tag：同时生成 getter + setter
// GetReadWrite 获取 ReadWrite
func (this *TagControl) GetReadWrite() int {
	return this.ReadWrite
}

// SetReadWrite 设置 ReadWrite
func (this *TagControl) SetReadWrite(ReadWrite int) {
	this.ReadWrite = ReadWrite
}

// AddReadWrite 将 ReadWrite 增加 delta
func (this *TagControl) AddReadWrite(delta int) {
	this.ReadWrite += delta
}

// SubReadWrite 将 ReadWrite 减少 delta
func (this *TagControl) SubReadWrite(delta int) {
	this.ReadWrite -= delta
}

// GetReadOnly 获取 ReadOnly
func (this *TagControl) GetReadOnly() int {
	return this.ReadOnly
}

// SetWriteOnly 设置 WriteOnly
func (this *TagControl) SetWriteOnly(WriteOnly int) {
	this.WriteOnly = WriteOnly
}

// AddWriteOnly 将 WriteOnly 增加 delta
func (this *TagControl) AddWriteOnly(delta int) {
	this.WriteOnly += delta
}

// SubWriteOnly 将 WriteOnly 减少 delta
func (this *TagControl) SubWriteOnly(delta int) {
	this.WriteOnly -= delta
}

// plain 模式测试：只生成核心 Get/Set，跳过扩展方法
// GetPlainBool 获取 PlainBool
func (this *TagControl) GetPlainBool() bool {
	return this.PlainBool
}

// SetPlainBool 设置 PlainBool
func (this *TagControl) SetPlainBool(PlainBool bool) {
	this.PlainBool = PlainBool
}

// Get/Set，无 Add/Sub
// GetPlainInt 获取 PlainInt
func (this *TagControl) GetPlainInt() int {
	return this.PlainInt
}

// SetPlainInt 设置 PlainInt
func (this *TagControl) SetPlainInt(PlainInt int) {
	this.PlainInt = PlainInt
}

// Get/Set，无 Has
// GetPlainPtr 获取 PlainPtr
func (this *TagControl) GetPlainPtr() *BaseInfo {
	return this.PlainPtr
}

// SetPlainPtr 设置 PlainPtr
func (this *TagControl) SetPlainPtr(PlainPtr *BaseInfo) {
	this.PlainPtr = PlainPtr
}

// At/Range/SetAt/Append/Delete，无 Len/Has/GetCopy
// GetPlainSliceAt 获取切片 PlainSlice 中 index 位置的元素
func (this *TagControl) GetPlainSliceAt(index int) string {
	return this.PlainSlice[index]
}

// RangePlainSlice 遍历切片 PlainSlice，fn 返回 false 时终止遍历
func (this *TagControl) RangePlainSlice(fn func(index int, value string) bool) {
	for i, v := range this.PlainSlice {
		if !fn(i, v) {
			break
		}
	}
}

// SetPlainSliceAt 设置切片 PlainSlice 中 index 位置的元素
func (this *TagControl) SetPlainSliceAt(index int, elem string) {
	this.PlainSlice[index] = elem
}

// AppendPlainSlice 向切片 PlainSlice 追加一个或多个元素
func (this *TagControl) AppendPlainSlice(elems ...string) {
	this.PlainSlice = append(this.PlainSlice, elems...)
}

// DeletePlainSliceAt 删除切片 PlainSlice 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *TagControl) DeletePlainSliceAt(index int) {
	this.PlainSlice = slices.Delete(this.PlainSlice, index, index+1)
}

// Val/Range/SetVal/DeleteKey，无 Has 系列
// GetPlainMapVal 获取 PlainMap 中指定 key 的值，ok 表示 key 是否存在
func (this *TagControl) GetPlainMapVal(key string) (int, bool) {
	val, ok := this.PlainMap[key]
	return val, ok
}

// RangePlainMap 遍历 PlainMap，fn 返回 false 时终止遍历
func (this *TagControl) RangePlainMap(fn func(key string, value int) bool) {
	for k, v := range this.PlainMap {
		if !fn(k, v) {
			break
		}
	}
}

// EnsurePlainMap 确保 PlainMap 已初始化（nil 时自动创建空 map），返回字段引用
func (this *TagControl) EnsurePlainMap() map[string]int {
	if this.PlainMap == nil {
		this.PlainMap = make(map[string]int)
	}
	return this.PlainMap
}

// SetPlainMapVal 设置 PlainMap 中指定 key 的值
func (this *TagControl) SetPlainMapVal(key string, value int) {
	this.PlainMap[key] = value
}

// DeletePlainMapKey 删除 PlainMap 中指定 key
func (this *TagControl) DeletePlainMapKey(key string) {
	delete(this.PlainMap, key)
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *TagControl) Reset() {
	*this = TagControl{}
}
