// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package examples

// 无 tag：同时生成 getter + setter
// GetReadWrite 获取 ReadWrite
func (this *TagControl) GetReadWrite() int {
	return this.ReadWrite
}

// SetReadWrite 设置 ReadWrite
func (this *TagControl) SetReadWrite(ReadWrite int) {
	this.ReadWrite = ReadWrite
}

// GetReadOnly 获取 ReadOnly
func (this *TagControl) GetReadOnly() int {
	return this.ReadOnly
}

// SetWriteOnly 设置 WriteOnly
func (this *TagControl) SetWriteOnly(WriteOnly int) {
	this.WriteOnly = WriteOnly
}
