// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package config

import "slices"

// Suffix 生成文件名后缀。对应 --suffix 标志。
// 例如 "access" → user_access.go；"gen" → user_gen.go。
// GetSuffix 获取 Suffix
func (this *File) GetSuffix() string {
	return this.Suffix
}

// SetSuffix 设置 Suffix
func (this *File) SetSuffix(Suffix string) {
	this.Suffix = Suffix
}

// Output 统一输出目录。对应 --output 标志。
// 空字符串表示与源文件同目录（默认行为）。
// GetOutput 获取 Output
func (this *File) GetOutput() string {
	return this.Output
}

// SetOutput 设置 Output
func (this *File) SetOutput(Output string) {
	this.Output = Output
}

// Excludes 额外排除的路径列表。对应多个 --exclude 标志。
// 支持纯目录名（如 "mock"）或路径前缀（如 "./proto"）。
// GetExcludesAt 获取切片 Excludes 中 index 位置的元素
func (this *File) GetExcludesAt(index int) string {
	return this.Excludes[index]
}

// GetExcludesLen 获取切片 Excludes 的长度
func (this *File) GetExcludesLen() int {
	return len(this.Excludes)
}

// RangeExcludes 遍历切片 Excludes，fn 返回 false 时终止遍历
func (this *File) RangeExcludes(fn func(index int, value string) bool) {
	for i, v := range this.Excludes {
		if !fn(i, v) {
			break
		}
	}
}

// HasExcludes 返回切片 Excludes 是否已初始化（非 nil）
func (this *File) HasExcludes() bool {
	return this.Excludes != nil
}

// GetExcludesCopy 返回切片 Excludes 的浅拷贝
func (this *File) GetExcludesCopy() []string {
	return slices.Clone(this.Excludes)
}

// SetExcludesAt 设置切片 Excludes 中 index 位置的元素
func (this *File) SetExcludesAt(index int, elem string) {
	this.Excludes[index] = elem
}

// AppendExcludes 向切片 Excludes 追加一个或多个元素
func (this *File) AppendExcludes(elems ...string) {
	this.Excludes = append(this.Excludes, elems...)
}

// DeleteExcludesAt 删除切片 Excludes 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *File) DeleteExcludesAt(index int) {
	this.Excludes = slices.Delete(this.Excludes, index, index+1)
}

// NoDefaultExcludes 禁用内置默认排除（vendor、testdata 等）。
// 对应 --no-default-excludes 标志。
// GetNoDefaultExcludes 获取 NoDefaultExcludes
func (this *File) GetNoDefaultExcludes() bool {
	return this.NoDefaultExcludes
}

// SetNoDefaultExcludes 设置 NoDefaultExcludes
func (this *File) SetNoDefaultExcludes(NoDefaultExcludes bool) {
	this.NoDefaultExcludes = NoDefaultExcludes
}
