// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 创建日期: 2026-03-06 16:49:47
// 该文件为自动生成，请勿修改！

package model

// 跳过此字段
// GetSkip 获取 Skip
func (this *FieldConfig) GetSkip() bool {
	return this.Skip
}

// SetSkip 设置 Skip
func (this *FieldConfig) SetSkip(Skip bool) {
	this.Skip = Skip
}

// 只读：只生成 getter
// GetReadonly 获取 Readonly
func (this *FieldConfig) GetReadonly() bool {
	return this.Readonly
}

// SetReadonly 设置 Readonly
func (this *FieldConfig) SetReadonly(Readonly bool) {
	this.Readonly = Readonly
}

// 只写：只生成 setter
// GetWriteOnly 获取 WriteOnly
func (this *FieldConfig) GetWriteOnly() bool {
	return this.WriteOnly
}

// SetWriteOnly 设置 WriteOnly
func (this *FieldConfig) SetWriteOnly(WriteOnly bool) {
	this.WriteOnly = WriteOnly
}
