// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

// 跳过此字段
// GetSkip 获取 Skip
func (this *FieldConfig) GetSkip() bool {
	return this.Skip
}

// SetSkip 设置 Skip
func (this *FieldConfig) SetSkip(Skip bool) {
	this.Skip = Skip
}

// 只读：只生成 getter
// GetReadonly 获取 Readonly
func (this *FieldConfig) GetReadonly() bool {
	return this.Readonly
}

// SetReadonly 设置 Readonly
func (this *FieldConfig) SetReadonly(Readonly bool) {
	this.Readonly = Readonly
}

// 只写：只生成 setter
// GetWriteOnly 获取 WriteOnly
func (this *FieldConfig) GetWriteOnly() bool {
	return this.WriteOnly
}

// SetWriteOnly 设置 WriteOnly
func (this *FieldConfig) SetWriteOnly(WriteOnly bool) {
	this.WriteOnly = WriteOnly
}

// 简单模式：跳过扩展方法，只保留核心访问器
// GetPlain 获取 Plain
func (this *FieldConfig) GetPlain() bool {
	return this.Plain
}

// SetPlain 设置 Plain
func (this *FieldConfig) SetPlain(Plain bool) {
	this.Plain = Plain
}

// 覆盖模式：忽略嵌入提升方法检查，强制生成（仍受字段名/手写方法约束）
// GetOverride 获取 Override
func (this *FieldConfig) GetOverride() bool {
	return this.Override
}

// SetOverride 设置 Override
func (this *FieldConfig) SetOverride(Override bool) {
	this.Override = Override
}

// 字段级覆盖，优先于 StructDef.DirtyMethod
// GetDirtyMethod 获取 DirtyMethod
func (this *FieldConfig) GetDirtyMethod() string {
	return this.DirtyMethod
}

// SetDirtyMethod 设置 DirtyMethod
func (this *FieldConfig) SetDirtyMethod(DirtyMethod string) {
	this.DirtyMethod = DirtyMethod
}

// Reset 将所有字段重置为零值。
// slice 和 map 字段重置为 nil，释放底层内存。
func (this *FieldConfig) Reset() {
	*this = FieldConfig{}
}
