// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

// 字段名，如 "Name"、"UserID"
// GetName 获取 Name
func (this *FieldDef) GetName() string {
	return this.Name
}

// SetName 设置 Name
func (this *FieldDef) SetName(Name string) {
	this.Name = Name
}

// 字段类型的完整描述
// GetType 获取 Type
func (this *FieldDef) GetType() *TypeInfo {
	return this.Type
}

// SetType 设置 Type
func (this *FieldDef) SetType(Type *TypeInfo) {
	this.Type = Type
}

// HasType 返回 Type 是否已初始化（非 nil）
func (this *FieldDef) HasType() bool {
	return this.Type != nil
}

// 从 struct tag 解析的生成配置
// GetConfig 获取 Config
func (this *FieldDef) GetConfig() FieldConfig {
	return this.Config
}

// SetConfig 设置 Config
func (this *FieldDef) SetConfig(Config FieldConfig) {
	this.Config = Config
}

// 字段上方的文档注释（field.Doc）
// GetDoc 获取 Doc
func (this *FieldDef) GetDoc() string {
	return this.Doc
}

// SetDoc 设置 Doc
func (this *FieldDef) SetDoc(Doc string) {
	this.Doc = Doc
}

// 字段行尾注释（field.Comment）
// GetComment 获取 Comment
func (this *FieldDef) GetComment() string {
	return this.Comment
}

// SetComment 设置 Comment
func (this *FieldDef) SetComment(Comment string) {
	this.Comment = Comment
}
