// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 创建日期: 2026-03-06 16:49:47
// 该文件为自动生成，请勿修改！

package model

// 结构体名，如 "User"
// GetName 获取 Name
func (this *StructDef) GetName() string {
	return this.Name
}

// SetName 设置 Name
func (this *StructDef) SetName(Name string) {
	this.Name = Name
}

// 所在包名，如 "model"
// GetPackageName 获取 PackageName
func (this *StructDef) GetPackageName() string {
	return this.PackageName
}

// SetPackageName 设置 PackageName
func (this *StructDef) SetPackageName(PackageName string) {
	this.PackageName = PackageName
}

// 包的导入路径，如 "github.com/foo/bar/model"
// GetPackagePath 获取 PackagePath
func (this *StructDef) GetPackagePath() string {
	return this.PackagePath
}

// SetPackagePath 设置 PackagePath
func (this *StructDef) SetPackagePath(PackagePath string) {
	this.PackagePath = PackagePath
}

// 源文件所在目录的绝对路径，用于输出文件
// GetDir 获取 Dir
func (this *StructDef) GetDir() string {
	return this.Dir
}

// SetDir 设置 Dir
func (this *StructDef) SetDir(Dir string) {
	this.Dir = Dir
}

// 字段列表（已过滤掉 Skip=true 的字段由生成层处理）
// GetFieldsElem 获取切片 Fields 中 index 位置的元素
func (this *StructDef) GetFieldsElem(index int) *FieldDef {
	return this.Fields[index]
}

// GetFieldsLen 获取切片 Fields 的长度
func (this *StructDef) GetFieldsLen() int {
	return len(this.Fields)
}

// GetFieldsCap 获取切片 Fields 的容量
func (this *StructDef) GetFieldsCap() int {
	return cap(this.Fields)
}

// RangeFields 遍历切片 Fields，fn 返回 false 时终止遍历
func (this *StructDef) RangeFields(fn func(index int, value *FieldDef) bool) {
	for i, v := range this.Fields {
		if !fn(i, v) {
			break
		}
	}
}

// SetFieldsElem 设置切片 Fields 中 index 位置的元素
func (this *StructDef) SetFieldsElem(index int, elem *FieldDef) {
	this.Fields[index] = elem
}

// AddFieldsElem 向切片 Fields 追加元素
func (this *StructDef) AddFieldsElem(elem *FieldDef) {
	this.Fields = append(this.Fields, elem)
}

// DelFieldsElem 删除切片 Fields 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *StructDef) DelFieldsElem(index int) {
	this.Fields = append(this.Fields[:index], this.Fields[index+1:]...)
}

// 结构体文档注释
// GetDoc 获取 Doc
func (this *StructDef) GetDoc() string {
	return this.Doc
}

// SetDoc 设置 Doc
func (this *StructDef) SetDoc(Doc string) {
	this.Doc = Doc
}
