// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

import "slices"

// GetKind 获取 Kind
func (this *TypeInfo) GetKind() TypeKind {
	return this.Kind
}

// SetKind 设置 Kind
func (this *TypeInfo) SetKind(Kind TypeKind) {
	this.Kind = Kind
}

// AddKind 将 Kind 增加 delta
func (this *TypeInfo) AddKind(delta TypeKind) {
	this.Kind += delta
}

// SubKind 将 Kind 减少 delta
func (this *TypeInfo) SubKind(delta TypeKind) {
	this.Kind -= delta
}

// 完整类型字符串，如 "[]string"、"map[string]int32"
// GetTypeStr 获取 TypeStr
func (this *TypeInfo) GetTypeStr() string {
	return this.TypeStr
}

// SetTypeStr 设置 TypeStr
func (this *TypeInfo) SetTypeStr(TypeStr string) {
	this.TypeStr = TypeStr
}

// slice/array/pointer 的元素类型
// GetElem 获取 Elem
func (this *TypeInfo) GetElem() *TypeInfo {
	return this.Elem
}

// SetElem 设置 Elem
func (this *TypeInfo) SetElem(Elem *TypeInfo) {
	this.Elem = Elem
}

// HasElem 返回 Elem 是否已初始化（非 nil）
func (this *TypeInfo) HasElem() bool {
	return this.Elem != nil
}

// map 的 key 类型
// GetKey 获取 Key
func (this *TypeInfo) GetKey() *TypeInfo {
	return this.Key
}

// SetKey 设置 Key
func (this *TypeInfo) SetKey(Key *TypeInfo) {
	this.Key = Key
}

// HasKey 返回 Key 是否已初始化（非 nil）
func (this *TypeInfo) HasKey() bool {
	return this.Key != nil
}

// map 的 value 类型
// GetValue 获取 Value
func (this *TypeInfo) GetValue() *TypeInfo {
	return this.Value
}

// SetValue 设置 Value
func (this *TypeInfo) SetValue(Value *TypeInfo) {
	this.Value = Value
}

// HasValue 返回 Value 是否已初始化（非 nil）
func (this *TypeInfo) HasValue() bool {
	return this.Value != nil
}

// array 的长度，如 "8"
// GetArrayLen 获取 ArrayLen
func (this *TypeInfo) GetArrayLen() string {
	return this.ArrayLen
}

// SetArrayLen 设置 ArrayLen
func (this *TypeInfo) SetArrayLen(ArrayLen string) {
	this.ArrayLen = ArrayLen
}

// 泛型类型参数，如 List[int] 中的 int
// GetTypeArgsAt 获取切片 TypeArgs 中 index 位置的元素
func (this *TypeInfo) GetTypeArgsAt(index int) *TypeInfo {
	return this.TypeArgs[index]
}

// GetTypeArgsLen 获取切片 TypeArgs 的长度
func (this *TypeInfo) GetTypeArgsLen() int {
	return len(this.TypeArgs)
}

// RangeTypeArgs 遍历切片 TypeArgs，fn 返回 false 时终止遍历
func (this *TypeInfo) RangeTypeArgs(fn func(index int, value *TypeInfo) bool) {
	for i, v := range this.TypeArgs {
		if !fn(i, v) {
			break
		}
	}
}

// HasTypeArgs 返回切片 TypeArgs 是否已初始化（非 nil）
func (this *TypeInfo) HasTypeArgs() bool {
	return this.TypeArgs != nil
}

// GetTypeArgsCopy 返回切片 TypeArgs 的浅拷贝
func (this *TypeInfo) GetTypeArgsCopy() []*TypeInfo {
	return slices.Clone(this.TypeArgs)
}

// SetTypeArgsAt 设置切片 TypeArgs 中 index 位置的元素
func (this *TypeInfo) SetTypeArgsAt(index int, elem *TypeInfo) {
	this.TypeArgs[index] = elem
}

// AppendTypeArgs 向切片 TypeArgs 追加一个或多个元素
func (this *TypeInfo) AppendTypeArgs(elems ...*TypeInfo) {
	this.TypeArgs = append(this.TypeArgs, elems...)
}

// DeleteTypeArgsAt 删除切片 TypeArgs 中 index 位置的元素，并清零释放的尾部槽位
// 注意：会改变被删除元素之后所有元素的下标
func (this *TypeInfo) DeleteTypeArgsAt(index int) {
	this.TypeArgs = slices.Delete(this.TypeArgs, index, index+1)
}

// 是否为类型别名（type X = T）
// GetIsAlias 获取 IsAlias
func (this *TypeInfo) GetIsAlias() bool {
	return this.IsAlias
}

// SetIsAlias 设置 IsAlias
func (this *TypeInfo) SetIsAlias(IsAlias bool) {
	this.IsAlias = IsAlias
}
