// Code generated by gogen; DO NOT EDIT.

// 版权所有(Copyright)[yangyuan]
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// 创建日期: 2026-03-06 16:49:47
// 该文件为自动生成，请勿修改！

package model

// GetKind 获取 Kind
func (this *TypeInfo) GetKind() TypeKind {
	return this.Kind
}

// SetKind 设置 Kind
func (this *TypeInfo) SetKind(Kind TypeKind) {
	this.Kind = Kind
}

// 完整类型字符串，如 "[]string"、"map[string]int32"
// GetTypeStr 获取 TypeStr
func (this *TypeInfo) GetTypeStr() string {
	return this.TypeStr
}

// SetTypeStr 设置 TypeStr
func (this *TypeInfo) SetTypeStr(TypeStr string) {
	this.TypeStr = TypeStr
}

// slice/array/pointer 的元素类型
// GetElem 获取 Elem
func (this *TypeInfo) GetElem() *TypeInfo {
	return this.Elem
}

// SetElem 设置 Elem
func (this *TypeInfo) SetElem(Elem *TypeInfo) {
	this.Elem = Elem
}

// map 的 key 类型
// GetKey 获取 Key
func (this *TypeInfo) GetKey() *TypeInfo {
	return this.Key
}

// SetKey 设置 Key
func (this *TypeInfo) SetKey(Key *TypeInfo) {
	this.Key = Key
}

// map 的 value 类型
// GetValue 获取 Value
func (this *TypeInfo) GetValue() *TypeInfo {
	return this.Value
}

// SetValue 设置 Value
func (this *TypeInfo) SetValue(Value *TypeInfo) {
	this.Value = Value
}

// array 的长度，如 "8"
// GetArrayLen 获取 ArrayLen
func (this *TypeInfo) GetArrayLen() string {
	return this.ArrayLen
}

// SetArrayLen 设置 ArrayLen
func (this *TypeInfo) SetArrayLen(ArrayLen string) {
	this.ArrayLen = ArrayLen
}

// 泛型类型参数，如 List[int] 中的 int
// GetTypeArgsElem 获取切片 TypeArgs 中 index 位置的元素
func (this *TypeInfo) GetTypeArgsElem(index int) *TypeInfo {
	return this.TypeArgs[index]
}

// GetTypeArgsLen 获取切片 TypeArgs 的长度
func (this *TypeInfo) GetTypeArgsLen() int {
	return len(this.TypeArgs)
}

// GetTypeArgsCap 获取切片 TypeArgs 的容量
func (this *TypeInfo) GetTypeArgsCap() int {
	return cap(this.TypeArgs)
}

// RangeTypeArgs 遍历切片 TypeArgs，fn 返回 false 时终止遍历
func (this *TypeInfo) RangeTypeArgs(fn func(index int, value *TypeInfo) bool) {
	for i, v := range this.TypeArgs {
		if !fn(i, v) {
			break
		}
	}
}

// SetTypeArgsElem 设置切片 TypeArgs 中 index 位置的元素
func (this *TypeInfo) SetTypeArgsElem(index int, elem *TypeInfo) {
	this.TypeArgs[index] = elem
}

// AddTypeArgsElem 向切片 TypeArgs 追加元素
func (this *TypeInfo) AddTypeArgsElem(elem *TypeInfo) {
	this.TypeArgs = append(this.TypeArgs, elem)
}

// DelTypeArgsElem 删除切片 TypeArgs 中 index 位置的元素
// 注意：会改变被删除元素之后所有元素的下标
func (this *TypeInfo) DelTypeArgsElem(index int) {
	this.TypeArgs = append(this.TypeArgs[:index], this.TypeArgs[index+1:]...)
}

// 是否为类型别名（type X = T）
// GetIsAlias 获取 IsAlias
func (this *TypeInfo) GetIsAlias() bool {
	return this.IsAlias
}

// SetIsAlias 设置 IsAlias
func (this *TypeInfo) SetIsAlias(IsAlias bool) {
	this.IsAlias = IsAlias
}
